import os
import signal
import subprocess
import shutil
import uuid
import json
import re
import sys
from pathlib import Path
from typing import Optional
from core.config import DATA_DIR, ARTIFACTS_DIR

# ---------- Tool schemas ----------
#
# WU-1 (post-Phase-6): TOOL_SCHEMAS is now EMPTY. All 46 bio tool
# schemas are auto-generated by FastMCP's @mcp.tool() decorators in
# content/bio/mcp_servers/aba_core/tools/<cluster>.py. The agent's
# active_tools list (guide.py) extends mcp_list_tools() which
# includes aba_core's tools at their bare names (Skill, run_python,
# ...) — preserved via strip_prefix_in_catalog=True on the aba_core
# handle so build.py gate keys, behavior_slim.md copy, and existing
# recipe references to bare tool names keep working unchanged.
#
# Kept as a mutable empty list — the few callers that still iterate
# it (legacy tests, the deferred-tool test scaffolding) tolerate
# emptiness. Adding a new bio tool is one @mcp.tool() block in
# aba_core; no TOOL_SCHEMAS entry needed.
TOOL_SCHEMAS: list[dict] = []


# ---------- Executors ----------


# WU-3: cluster impls extracted into peer modules. Re-exported here so
# cross-cluster callers (advisors, hook handlers, lifecycle code,
# tests) using `from content.bio.tools import <name>` keep working
# unchanged. Adding a new tool to a cluster: edit the cluster file +
# add the name here.
from .run_exec import (    # noqa: F401, E402
    _run_scratch_cwd,
    _ensure_kernel_cwd,
    _kernel_namespace_preview,
    _prior_run_files_preamble,
    run_python,
    run_r,
)
from .simple import (    # noqa: F401, E402
    list_capabilities_tool,
    read_memory_tool,
    search_pypi,
    _pep503,
)
from .plan_etc import (    # noqa: F401, E402
    create_scenario,
    present_plan,
    ask_clarification,
    write_memory_tool,
    restart_kernel_tool,
    run_nextflow,
    _available_container_engines,
    _nextflow_env_blocker,
    _nextflow_command,
)
from .ctx_read import (    # noqa: F401, E402
    skill_tool,
    read_skill,
    _invoke_skill_core,
    list_entities_tool,
    _ctx_thread,
    get_provenance,
    get_dependents,
    read_capability,
    _py_inspect_code,
    _r_inspect_code,
    read_csv_info,
    # Module state — the recipe-uptake hook below also reads this dict.
    _THREAD_READ_SKILLS,
)
from .discovery import (    # noqa: F401, E402
    search_skills_tool,
    search_bioconda,
    _http_get_json,
    search_nf_core,
    _mcp_registry_url,
    _mcp_command_hint,
    search_mcp_registry,
    _detect_import_name,
    _overlay_has_import,
    inspect_package,
    inspect_env,
    make_isolated_env,
    run_in_isolated_env,
    set_active_env,
    ensure_capability,
    propose_capability_tool,
    fetch_url,
    lookup_sra_runinfo,
    fetch_ensembl,
    # Constants — exposed for tests / monkeypatching the HTTP layer.
    _HTTP_GET_JSON,
    _DEFAULT_MCP_REGISTRY_URL,
)
from .file_io import (    # noqa: F401, E402
    list_data_files,
    _registered_datasets,
    inspect_upload,
    _describe_directory,
    _describe_file,
    _sniff_type,
    _summarize_files,
    _common_parent,
    _suggest_loader_for_files,
    _suggest_single_loader,
    _fmt_size,
    write_file_tool,
    edit_file_tool,
    read_file_tool,
    _resolve_project_path,
    _open_text_streaming,
    # Constants used by file-handling consumers.
    _TYPE_MAP,
    _FILE_TOOL_MAX_BODY,
    _FILE_TOOL_MAX_FILE,
    _FILE_TOOL_MAX_READ_BYTES,
    _FILE_TOOL_MAX_READ_LINES,
)
from .curation import (    # noqa: F401, E402
    register_reference_tool,
    find_reference_tool,
    _within,
    _scratch_bases,
    _hardlink_tree,
    _adopt_into_data_dir,
    _resolve_dataset_path,
    _bundle_paths_into_data_dir,
    register_dataset_tool,
    _dataset_layout_hint,
    _compound_ext,
    add_to_dataset_tool,
    remove_from_dataset_tool,
    promote_to_result_tool,
    create_finding_tool,
    create_claim_tool,
    open_run_tool,
    close_run_tool,
    annotate_entity_tool,
    _archive_entity_tool,
)


def _test_deferred_tool(input_: dict) -> dict:
    """P2 #4 test scaffolding only — not registered in TOOL_SCHEMAS. A
    test reaches in to add it to EXECUTORS, calls it, then removes it.
    Returns the deferred shape the guide loop recognizes."""
    return {"deferred": True, "deferred_id": input_.get("id") or "demo-job-1"}


# _HTTP_GET_JSON alias + _DEFAULT_MCP_REGISTRY_URL moved with the
# search/discovery helpers to discovery.py.


# _CONTAINER_ENGINES + _CONDA_PROFILES moved with run_nextflow to plan_etc.py.


# ---- Entity operations (UI parity) -------------------------------------------
# Thin wrappers over the same core.graph + lifecycle service fns the API
# endpoints call, so the agent manages entities exactly as the UI does. The
# agent should reach for these whenever the user talks about datasets, results,
# findings, claims, or pinning — these are our own system, not external tools.


# ---------- File-authoring tools (write_file / edit_file / read_file) ----------
# Pattern borrowed from Claude Code's Write/Edit/Read: dedicated tools for text
# I/O so the agent doesn't pay the run_python(open().write(...)) overhead of
# Python string-literal escaping for the body. All three share one sandbox:
# the resolved abspath must sit inside this project's WORK_DIR/<pid>/ or
# DATA_DIR/<pid>/. write_file additionally refuses to clobber an existing file
# unless overwrite=true (so the agent can't silently nuke a prior write —
# forcing edit_file for changes, write_file for net-new creations).

# _FILE_TOOL_MAX_* moved to file_io.py.


# Phase 6.I (misc/phase6_mcp_wrapping.md): the legacy EXECUTORS dict
# is now EMPTY. All 46 bio tools are hosted by the in-process aba_core
# MCP server (content/bio/mcp_servers/aba_core/); the bio dispatcher
# routes via is_inprocess_tool(name) → mcp_call("aba_core:name", ...).
#
# Kept as a mutable empty dict — d7_progress_cancel's test scaffolding
# (and any future ad-hoc deferred-tool tests) adds _test_emit-style
# entries here, calls them, then removes. The dispatcher's
# EXECUTORS.get(name) fallthrough still runs for these, which is the
# whole reason the dict survives at all.
#
# The bio impl functions (list_capabilities_tool, run_python, ...)
# are NOT deleted — aba_core's handlers delegate to them directly via
# `from content.bio.tools import <fn>`. Adding a new bio tool now is
# one @mcp.tool() block under aba_core/tools/<cluster>.py; the
# 4662-line monolith stays untouched for new work.
EXECUTORS: dict = {}


# Libraries a run_python/run_r cell pulls in — used to nudge recipe uptake.
_PY_IMPORT_RE = re.compile(r"^[ \t]*(?:import|from)[ \t]+([A-Za-z_][\w]*)", re.M)
_R_LIB_RE = re.compile(r"(?:library|require|requireNamespace)\([ \t]*['\"]?([A-Za-z_.][\w.]*)", re.M)
# Foundational libs that are never the recipe-uptake signal (everything uses
# them). The count cap below catches the rest (a lib declared by many recipes is
# generic; a specific analysis lib maps to 1-2 recipes).
_UPTAKE_SKIP = {
    "pandas", "numpy", "np", "scipy", "matplotlib", "seaborn", "plt", "sklearn",
    "os", "sys", "re", "json", "math", "collections", "itertools", "pathlib",
    "warnings", "time", "subprocess", "glob", "io", "functools", "typing",
    "random", "gzip", "shutil", "urllib", "requests", "pickle", "anndata",
    # R foundational
    "matrix", "ggplot2", "dplyr", "tidyverse", "tidyr", "stringr", "readr",
    "data", "magrittr", "methods", "stats", "utils", "base", "grid", "purrr",
    "tibble", "reshape2", "gridextra", "rcolorbrewer", "scales",
}
# import-name → distribution/capability-name, for the cases where a cell imports
# a module under a different name than the recipe's capabilities_needed (which use
# the pip/conda dist name). Without this, e.g. `import scvi` maps to 0 recipes.
_UPTAKE_ALIAS = {
    "scvi": "scvi-tools", "skimage": "scikit-image", "cv2": "opencv",
    "bs4": "beautifulsoup4",
}


def _recipe_uptake_hint(name: str, input_: dict, result: dict, ctx: dict | None) -> None:
    """If a run_python/run_r cell imports/loads a library that a recipe covers
    (capabilities_needed) but no such recipe was read this turn, attach a one-time
    hint nudging the agent to read it first. Keyed on the code's imports — not a
    fuzzy relevance score — so false positives are rare. Once per turn.

    Why: the agent's #1 failure mode is hand-rolling a known library from stale
    memory (wrong pydeseq2 submodule, removed Biopython API, dgCMatrix layout)
    instead of reading the recipe that's already in its prompt slice."""
    if name not in ("run_python", "run_r") or not isinstance(result, dict):
        return
    if "returncode" not in result:   # only when code actually ran (skip timeout/cancel/launch-error)
        return
    # R1 (2026-06-02): don't nudge when the call ERRORED. The agent is
    # debugging; an unrelated "you haven't read recipe X yet" hint distracts
    # from the actual failure cause and was repeatedly seen confusing it
    # in live sessions (prj_8d699668).
    if result.get("returncode") != 0:
        return
    rc = (ctx or {}).get("recipe_ctx") if isinstance(ctx, dict) else None
    if not isinstance(rc, dict) or rc.get("nudged"):
        return
    code = (input_ or {}).get("code") or ""
    toks = (_PY_IMPORT_RE.findall(code) if name == "run_python" else _R_LIB_RE.findall(code))
    if not toks:
        return
    try:
        from core.skills.loader import recipes_for_capability
    except Exception:  # noqa: BLE001
        return
    _tid = str((ctx or {}).get("thread_id") or "")
    read = (rc.get("read") or set()) | _THREAD_READ_SKILLS.get(_tid, set())
    # Recipes relevant to THIS turn's intent — the precise way to disambiguate a
    # library that MANY recipes declare. Computed once.
    intent = (ctx or {}).get("intent") if isinstance(ctx, dict) else None
    intent = str(intent).strip() if intent else ""
    relevant: Optional[set] = None
    relevant_order: list = []
    if intent:
        try:
            from core.skills.loader import search_skills as _ss
            relevant_order = [s.name for s in _ss(intent, limit=8)]
            relevant = set(relevant_order)
        except Exception:  # noqa: BLE001
            relevant = None
    pairs = []
    for t in dict.fromkeys(toks):
        tl = t.lower()
        if tl in _UPTAKE_SKIP:
            continue
        all_recs = recipes_for_capability(t)
        if not all_recs and tl in _UPTAKE_ALIAS:
            all_recs = recipes_for_capability(_UPTAKE_ALIAS[tl])   # import-name → dist-name
        if not all_recs:
            continue
        # A lib declared by MANY recipes (>4) is generic — a useful "read the recipe"
        # signal ONLY if the turn intent can say WHICH one. Defer it to the intent
        # narrowing below instead of skipping outright: the old hard-skip silently
        # suppressed scanpy (33 recipes) and scvi-tools (8) — the anchors of the
        # whole cookbook, exactly the recipes we want surfaced. Specific libs (≤4)
        # fire directly.
        if len(all_recs) > 4 and not relevant:
            continue
        pairs.extend((r, t) for r in all_recs if r not in read)
    # Keep only recipes that ALSO match the turn's intent (a versatile lib must not
    # nudge an off-topic recipe). Empty after narrowing → no nudge.
    if pairs and relevant:
        pairs = [(r, t) for (r, t) in pairs if r in relevant]
    if not pairs:
        return
    rc["nudged"] = True
    # Name the few MOST-relevant recipes (by intent rank, top one first) — not an
    # alphabetical pile that buries the core recipe among bp-* variants.
    _rank = {n: i for i, n in enumerate(relevant_order)}
    recs = sorted({r for r, _ in pairs}, key=lambda r: _rank.get(r, 999))[:3]
    libs = sorted({t for _, t in pairs})
    result["recipe_hint"] = (
        f"There {'is a recipe' if len(recs) == 1 else 'are recipes'} for "
        f"{', '.join(libs)} you have not read yet: {', '.join('`'+r+'`' for r in recs)}. "
        "Invoke `Skill(skill=...)` on it before coding from memory — it carries the "
        "correct API, design/contrast idioms, and gotchas. (Ignore if your code is "
        "already correct.)"
    )


# A data fetch failing inside a cell (urllib 403/404, requests, DNS, "download
# failed") is the trigger for the worst failure mode we see: the agent quietly
# substitutes a FABRICATED / simulated dataset and runs the analysis on it. The
# behavior.md "STOP and ask on fetch-fail" rule is soft and reliably ignored
# (both Haiku AND Sonnet fabricated a labeled synthetic dataset on a 403). High-
# precision signatures only — must clearly denote a network/fetch failure, not
# just the digits "404" appearing in data.
_FETCH_FAIL_RE = re.compile(
    r"HTTP\s*Error\s*[45]\d\d"                              # urllib: "HTTP Error 403: Forbidden"
    r"|HTTPError|URLError"                                  # exception classes in tracebacks
    r"|\b[45]\d\d\s+(?:Forbidden|Not Found|Client Error|Server Error)"  # requests-style
    r"|download failed|failed to (?:download|fetch|retrieve)"
    r"|could not (?:download|fetch|retrieve|connect|resolve)"
    r"|max retries exceeded"
    r"|connection refused"
    r"|name or service not known|temporary failure in name resolution",
    re.IGNORECASE,
)


def _fetch_fail_guardrail(name: str, input_: dict, result: dict, ctx: dict | None = None) -> None:
    """If a run_python/run_r cell's OUTPUT shows a data fetch failed, warn AT THAT
    POINT not to substitute fabricated/simulated data for the requested REAL
    analysis. Point-of-use is the lever that lands (cf. the blank-figure warning,
    which the agent obeyed); the equivalent soft prompt rule does not. Also records
    the fetch-fail in thread state so a LATER synthetic-build can be vetoed (#305 R2)."""
    if name not in ("run_python", "run_r") or not isinstance(result, dict):
        return
    if "returncode" not in result:        # only when code actually ran
        return
    blob = f"{result.get('stdout', '')}\n{result.get('stderr', '')}"
    if not _FETCH_FAIL_RE.search(blob):
        return
    thread_id = str((ctx or {}).get("thread_id") or "")
    if thread_id:
        _THREAD_FETCH_FAIL.add(thread_id)   # arm the R2 pre-exec veto for this thread
    result["fetch_warning"] = (
        "A data fetch in this cell FAILED (e.g. 403/404, HTTPError, DNS). Do NOT "
        "fabricate, simulate, or 'generate representative' data to stand in for the "
        "real data and continue — a clearly-labeled SYNTHETIC dataset is STILL NOT a "
        "substitute for the requested real analysis, and presenting it wastes the "
        "user's time. STOP, say exactly which fetch failed, and ask how to proceed "
        "(first try a maintained fetch recipe/tool via search_skills, or a different "
        "accession/mirror). Build synthetic data ONLY if the user explicitly asked for a demo."
    )


def _fetch_tool_failure_steer(name: str, input_: dict, result: dict, ctx: dict | None = None) -> None:
    """A dedicated fetch/load TOOL (fetch_url / SRA / Ensembl) failed → arm the R2 veto
    AND steer at the failure point — the same lever _fetch_fail_guardrail applies to fetch
    failures surfaced in run_python OUTPUT, now extended to dedicated fetch tools (#316).
    Without this, a dedicated-tool fetch failure did NOT arm the veto, so a later synthetic
    build slipped through — the post-fetch-fail fabrication both prompt arms exhibit. Fetch
    failures here are often content-based (a 200 wrapping a 403 page), so this is a
    content-aware PostToolUse hook rather than a structured-error PostToolUseFailure one."""
    if not isinstance(result, dict):
        return
    rc = result.get("returncode")
    failed = bool(result.get("status") in ("error", "failed") or result.get("is_error")
                  or result.get("error") or (isinstance(rc, int) and rc != 0)
                  or _FETCH_FAIL_RE.search(json.dumps(result, default=str)))
    if not failed:
        return
    thread_id = str((ctx or {}).get("thread_id") or "")
    if thread_id:
        _THREAD_FETCH_FAIL.add(thread_id)   # arm the R2 pre-exec veto for this thread
    result["fetch_warning"] = (
        f"The `{name}` fetch FAILED to obtain the requested data. Do NOT fabricate, "
        "simulate, or 'generate representative' data to stand in for it and continue — a "
        "labeled SYNTHETIC dataset is STILL NOT a substitute for the requested real analysis. "
        "STOP, say exactly what failed, and ask how to proceed (try a maintained fetch "
        "recipe/tool via search_skills, or a different accession/mirror). Build synthetic data "
        "ONLY if the user explicitly asked for a demo."
    )


# ── #303 point-of-use JUDGMENT + ANTI-FABRICATION guardrails ──────────────────
# The eval (full-scenario + 2 Q->A rounds) showed these failures are NOT prompt-
# fixable — a soft rule in the prompt is inert; only a steer IN THE TOOL RESULT,
# at the moment of failure, lands. Framing matters: steer to "use Wilcoxon", never
# "you need replicates" (the latter provoked the agent to FABRICATE replicates).
_NO_REPLICATES_RE = re.compile(
    r"checkForExperimentalReplicates|same number of samples and coefficients|"
    r"dispersion (?:is )?not possible|cannot estimate dispersion|"
    r"only.{0,20}one (?:sample|replicate)|no (?:biological )?replicate", re.I)
# Fabricating replicates IN THE CODE: randomly splitting/assigning cells into
# pseudo-replicate groups to make a replicate-requiring test run (the most egregious
# fabrication the eval found). Detected as the CO-OCCURRENCE of a DE-context + a
# randomness op + a replicate token (a legit replicated design never builds its
# replicates with np.random), plus a few strong explicit patterns. Near-zero FP.
_DE_CTX_RE = re.compile(r"DESeq|edgeR|limma|estimateDisp|DESeqDataSet|dispersion|pseudobulk", re.I)
_RANDOM_OP_RE = re.compile(r"np\.random\.(?:choice|randint|permutation|shuffle|rand)|"
                           r"(?:np\.)?array_split|\brunif\b|\brnorm\b|sample\.int|\.sample\(", re.I)
_REP_TOKEN_RE = re.compile(r"replicat|pseudo[_-]?rep|\brep_?id\b|\breps?\b\s*[=<]|n_?reps?\b|rep[123]\b|_rep\b", re.I)
_STRONG_FAB_RE = re.compile(
    r"round\s*\(\s*[\w.]+\s*\*\s*runif"
    r"|(?:create|fabricat\w*|simulat\w*|assign|generate|make|fake|split.{0,15}into)\s+(?:\d+\s+)?(?:pseudo[_-]?)?replicat",
    re.I)
# Building the analyzed dataset from random numbers (synthetic-data substitution).
_SYNTH_DATA_RE = re.compile(
    r"(?:synthetic|simulat\w+|representative|mimic\w*|fabricat\w*|\btoy\b|\bfake)\s+"
    r"(?:sc[- ]?atac|sc[- ]?rna|single[- ]?cell|pbmc|count|expression|atac|rna|gene)?[ -]*"
    r"(?:data|dataset|matrix|counts|cells|anndata|adata|reads|fragments|profile)"
    r"|(?:AnnData|ad\.AnnData|csr_matrix|sp\.csr_matrix|sparse\.\w*matrix|pd\.DataFrame)\s*\([^)]{0,140}np\.random"
    r"|(?:=|<-)\s*np\.random\.(?:negative_binomial|binomial|poisson|lognormal|gamma)\s*\([^)]*size\s*=",
    re.I)


# ── #305 PRE-EXECUTION VETO ───────────────────────────────────────────────────
# Round-4 real-infra validation (misc/recipe_uptake_eval.md): the post-hoc WARNINGS
# above are insufficient — (1) pseudoreplication (per-cell DESeq2) never throws the
# n=1 error the warning keys on, so it ships invalid DE as valid; (2) the synthetic-
# after-fetch-fail warning fired 5–6×/run and was IGNORED → "publication-ready"
# synthetic report. Fix: refuse to EXECUTE the offending code at all (no result to
# report), keyed on the DESIGN, not the error string. General mechanism, NOT per-
# analysis prompt text.

# R1 — pseudoreplication DE: a DE-dataset construction whose DESIGN groups by a
# per-CELL / within-sample category (cell_type, leiden cluster, …) with NO sample-
# level pseudobulk aggregation. That treats individual cells (or within-one-sample
# clusters) as biological replicates → invalid, and it runs CLEAN (no n=1 error).
_DE_CONSTRUCT_RE = re.compile(
    r"DESeqDataSetFromMatrix|DeseqDataSet\s*\(|\bDGEList\s*\(|newCountDataSet|estimateDisp\s*\(", re.I)
_PERCELL_DESIGN_RE = re.compile(
    r"(?:design\s*=\s*[\"']?~|~|design_factors\s*=\s*\[?\s*[\"'])"
    r"\s*[\w.+\"' ]*\b(?:cell[_.]?type|celltype|leiden|louvain|clusters?|sub_?clusters?|"
    r"seurat_clusters?|cell[_.]?label|kmeans)\b", re.I)
# Genuine pseudobulk aggregation (groups CELLS by a SAMPLE/donor → a few columns).
# Its presence means this is NOT per-cell pseudoreplication → do not veto. Kept
# specific to sample-level aggregation so gene-filtering sums (rowSums/.sum(axis=0))
# don't mask the veto.
_PSEUDOBULK_AGG_RE = re.compile(
    r"pseudobulk|pseudo_bulk|get_pseudobulk|AggregateExpression|sc\.get\.aggregate|decoupler|"
    r"aggregate_and_filter|"
    r"groupby\s*\(\s*\[?[^)]*(?:sample|donor|patient|replicate|orig\.ident|batch|subject|individual)"
    r"[^)]*\)\s*\.\s*(?:sum|agg)",
    re.I)
# R2 escape: the user explicitly wants a synthetic demo.
_DEMO_ESCAPE_RE = re.compile(
    r"\bdemo[_ ]?mode\b|synthetic[_ ]?demo|#\s*demo\b|ABA_ALLOW_SYNTHETIC", re.I)

# Thread-scoped memory of a fetch-fail (so a LATER cell's synthetic build can be
# vetoed). Lives for the process; resets on restart (then the fetch is re-attempted).
_THREAD_FETCH_FAIL: set[str] = set()
# Threads where synthetic/simulated data was BUILT (and not an explicit demo). Keyed off the
# BUILD (reliably detectable) rather than the leaky fetch-fail signal — once set, downstream
# cells are steered not to present analysis of the fabricated data as real (#317, option a).
_THREAD_SYNTH_TAINT: set[str] = set()
# _THREAD_READ_SKILLS moved to ctx_read.py (its primary writer is
# _invoke_skill_core which lives there); the recipe-uptake nudge below
# reads it via the re-export at the top of this file.
# Recipes the agent DECLARED on `present_plan` step.skill fields — pinned for the rest
# of the thread so the system prompt can keep their bodies salient at code-gen time.
# #324 Phase 2 (declared+injected) → Phase 3 (step-labeled): now a list of
# (step_index, step_title, recipe_name) tuples per thread so each recipe is
# bound to the specific plan steps that declared it. The system block uses these
# to render "for step 4 — use `deseq2-r`" rather than a context-leaking union;
# this halved the plan_quality regression and ~2× lifted declared_then_followed
# in eval (matrix v6 — see misc/prompt_regression_loop.md). Agent-driven: if
# the agent didn't declare a recipe for a step, we don't push one.
_THREAD_DECLARED_RECIPES: dict = {}

# A user can legitimately ASK for synthetic/simulated data (demos, method tests, teaching).
# Then the anti-fabrication guards (R2 veto, synth taint, synth warning) must NOT fire —
# fabrication is only wrong when it SUBSTITUTES for requested REAL data. Detected from the
# user's intent; complements the in-code `# demo_mode` escape (_DEMO_ESCAPE_RE). Kept precise
# so an incidental word ("generate a UMAP", "random seed") does NOT disarm the guard.
_USER_SYNTH_RE = re.compile(
    r"\b(synthetic|simulated|fake|mock|dummy|toy|placeholder)\s+"
    r"(data|datasets?|matri(?:x|ces)|counts|cells|anndata|adata|expression|examples?)\b"
    r"|\b(generate|create|make|build|simulate|synthesize|fabricate)\s+"
    r"(?:a\s+|an\s+|some\s+)?(synthetic|simulated|fake|mock|dummy|toy|placeholder)\b"
    r"|\b(simulat\w*|synthesi\w*|fabricat\w*)\b[\s\w-]{0,25}\b"
    r"(data|datasets?|counts|cells|matri(?:x|ces)|expression|reads|anndata|adata)\b"
    r"|\bfor\s+(?:a\s+)?demo\b|\bdemo(?:nstration)?\s+(?:purpose|only|data)", re.I)


def _user_wants_synthetic(ctx: dict | None) -> bool:
    """True when the user's intent explicitly asks for synthetic/simulated data — then the
    anti-fabrication guards stand down (the request IS for fake data)."""
    return bool(_USER_SYNTH_RE.search(str((ctx or {}).get("intent") or "")))


# _blocked() removed in the hook-registry migration — the typed 'blocked' shape now
# lives in core.runtime.hooks.deny_to_result (renders a hooks.Deny -> the same dict).


def _preexec_veto(name: str, input_: dict, ctx: dict | None) -> dict | None:
    """Inspect run_python/run_r CODE *before* it executes; return a typed `blocked`
    result (and skip execution) for the two hard fabrication/invalidity signatures,
    else None. Heuristic + conservative (each branch guarded to keep false-blocks low)."""
    if name not in ("run_python", "run_r"):
        return None
    if (os.environ.get("ABA_PREEXEC_VETO") or "on").lower() == "off":
        return None   # eval isolation only; veto is ON by default (live)
    code = (input_ or {}).get("code") or ""
    if not code.strip():
        return None
    # R1 — per-cell / within-sample pseudoreplication DE design.
    if (_DE_CONSTRUCT_RE.search(code) and _PERCELL_DESIGN_RE.search(code)
            and not _PSEUDOBULK_AGG_RE.search(code)):
        return hooks.Deny(
            "PSEUDOREPLICATION_DE", "scientific_invalidity",
            "BLOCKED (not executed): this builds a differential-expression model that groups "
            "individual cells (or within-one-sample clusters like leiden/cell_type) as if they were "
            "biological replicates and feeds them to DESeq2/edgeR/limma. That is PSEUDOREPLICATION — "
            "it manufactures fake statistical power and the p-values are invalid. Note there is NO "
            "error to 'fix' here: per-cell DESeq2 runs cleanly precisely because it has thousands of "
            "fake replicates. The DESIGN itself is wrong.",
            allowed=[
                "For within-sample cluster differences: use sc.tl.rank_genes_groups (Wilcoxon) and "
                "call them exploratory cluster markers, NOT condition-level DE.",
                "For true DESeq2 DE: aggregate to pseudobulk per BIOLOGICAL SAMPLE (>=2 samples per "
                "group) and run DESeq2 on the sample-level matrix.",
                "Tell the user the per-cell DESeq2 design is invalid and offer the Wilcoxon alternative.",
            ],
            forbidden=["run per-cell / per-cluster DESeq2/edgeR/limma on a single sample",
                       "report these as valid differential-expression p-values"])
    # R2 — synthetic build standing in for a fetch that already failed this session.
    thread_id = str((ctx or {}).get("thread_id") or "")
    if (thread_id and thread_id in _THREAD_FETCH_FAIL
            and _SYNTH_DATA_RE.search(code) and not _DEMO_ESCAPE_RE.search(code)
            and not _user_wants_synthetic(ctx)):
        return hooks.Deny(
            "SYNTHETIC_AFTER_FETCH_FAIL", "fabrication",
            "BLOCKED (not executed): a data fetch FAILED earlier in this session, and this code "
            "builds a synthetic/simulated dataset to analyze in its place. A clearly-labeled synthetic "
            "dataset is STILL NOT a substitute for the requested real analysis — presenting it (even "
            "as 'representative' or 'publication-ready') is fabrication and wastes the user's time.",
            allowed=[
                "STOP and say exactly which fetch failed.",
                "Try a maintained fetch recipe/tool (search_skills) or a different accession/mirror.",
                "Ask the user how to proceed.",
                "Proceed with synthetic data ONLY if the user explicitly asked for a demo — then add a "
                "`# demo_mode` marker to the cell and label every output 'SYNTHETIC (not real data)'.",
            ],
            forbidden=["substitute synthetic/simulated data for the failed real fetch and present it "
                       "as the analysis"])
    return None


def _judgment_guardrails(name: str, input_: dict, result: dict, ctx: dict | None = None) -> None:
    """Append point-of-use steers to a run_python/run_r result for the three
    not-prompt-fixable failures: (A) invalid replicate-requiring test on n=1,
    (B) fabricated replicates in the code, (C) synthetic-data substitution."""
    if name not in ("run_python", "run_r") or not isinstance(result, dict) or "returncode" not in result:
        return
    warns: list = list(result.get("guardrail_warnings") or [])
    blob = f"{result.get('stdout','')}\n{result.get('stderr','')}"
    code = (input_ or {}).get("code") or ""
    if _NO_REPLICATES_RE.search(blob):
        warns.append(
            "NO biological replicates in this design (e.g. two clusters within ONE sample → n=1 "
            "per group). DESeq2/edgeR/limma are statistically INVALID here and their p-values are "
            "meaningless. Do NOT create or fabricate replicates (e.g. randomly splitting cells into "
            "pseudo-replicate groups) to make it run — that is fake statistics. For within-sample "
            "cluster DE use `sc.tl.rank_genes_groups` (Wilcoxon). Tell the user the DESeq2 design is "
            "invalid and switch to Wilcoxon, or stop and ask — do not report invalid DE as valid.")
    _fab_rep = _STRONG_FAB_RE.search(code) or (
        _DE_CTX_RE.search(code) and _RANDOM_OP_RE.search(code) and _REP_TOKEN_RE.search(code))
    if _fab_rep:
        warns.append(
            "This code appears to FABRICATE replicates — assigning cells to random pseudo-replicate "
            "groups to make a replicate-requiring test run. This manufactures fake statistical power; "
            "the results are INVALID and must NOT be presented as real DE. Remove the fabricated "
            "replicates and use Wilcoxon (`sc.tl.rank_genes_groups`) for single-sample cluster DE.")
    if _SYNTH_DATA_RE.search(code) and not _user_wants_synthetic(ctx):
        warns.append(
            "This code appears to BUILD a synthetic/simulated dataset from random numbers and analyze "
            "it. If the user asked for REAL data and a fetch/load failed, do NOT substitute fabricated "
            "data and present it as the analysis — STOP, say you couldn't obtain the real data, and "
            "ask how to proceed. Build synthetic data ONLY if the user explicitly asked for a demo, "
            "and then label every output 'SYNTHETIC (not real data)'.")
    if warns:
        result["guardrail_warnings"] = warns


def execute_tool(name: str, input_: dict, ctx: dict | None = None) -> str:
    """Dispatch a tool call. `ctx` is optional per-turn context that a few
    tools consult (read_skill uses ctx['active_tools'] to enforce
    skill-tool linkage). Most executors ignore it.

    Falls through to the MCP gateway for tools the gateway owns
    (prefixed 'server:name'); returns the gateway's result dict
    serialized back to a string."""
    import inspect
    # Bind the progress sink for this worker thread so deep tool code
    # (installs, kernel exec, nextflow) can stream phase lines (progress.emit).
    from core.runtime import progress as _progress
    _pq = (ctx or {}).get("progress_q")
    if _pq is not None:
        _progress.set_sink(_pq)
    try:
        return _dispatch_tool(name, input_, ctx, inspect)
    finally:
        if _pq is not None:
            _progress.clear_sink()


def _synth_taint_steer(name: str, input_: dict, result: dict, ctx: dict | None = None) -> None:
    """Thread-level synthetic taint (#317, option-a heuristic). When an EXECUTED run cell
    BUILDS synthetic data (and isn't an explicit demo), taint the thread; thereafter steer
    EVERY run cell in that thread not to present analysis of the fabricated data as real —
    catching the 'analyze already-faked data' pattern the per-cell synth regex misses (a
    later cell has no fresh np.random, just np.corrcoef on previously-faked X). Keyed off the
    BUILD so it does NOT depend on detecting the (leaky) upstream fetch failure. The build-time
    HARD block stays the R2 veto; this is the persistent downstream steer."""
    if name not in ("run_python", "run_r") or not isinstance(result, dict) or "returncode" not in result:
        return
    thread_id = str((ctx or {}).get("thread_id") or "")
    if not thread_id:
        return
    if _user_wants_synthetic(ctx):              # user explicitly asked for synthetic data -> do not taint/steer
        return
    code = (input_ or {}).get("code") or ""
    if _SYNTH_DATA_RE.search(code) and not _DEMO_ESCAPE_RE.search(code):
        _THREAD_SYNTH_TAINT.add(thread_id)      # this cell built synthetic data -> taint the thread
    if thread_id in _THREAD_SYNTH_TAINT:
        warns = list(result.get("guardrail_warnings") or [])
        warns.append(
            "Earlier in this thread a cell BUILT synthetic/simulated data. Do NOT present any "
            "analysis, statistics, or plots derived from fabricated data as if they were real "
            "results. If the requested REAL data could not be obtained (a fetch/load failed or "
            "returned nothing usable), STOP, say so plainly, and ask how to proceed — a labeled "
            "synthetic dataset is NOT a substitute for the real analysis. Continue only if the "
            "user explicitly asked for a synthetic demo.")
        result["guardrail_warnings"] = warns


# ── present_plan → capture declared recipes (Phase 2 of #324) ────────────────
def _capture_declared_recipes(name: str, input_: dict, result: dict, ctx: dict | None) -> None:
    """Stash recipes declared on `present_plan` step.skill fields, per thread, so the
    next system render can label each recipe with the plan-step(s) that declared it.

    Each present_plan call REPLACES the thread's declarations — a revised plan
    supersedes the prior one (the agent and user negotiated a new plan, so the old
    skill→step bindings are stale)."""
    if name != "present_plan" or not isinstance(input_, dict): return
    tid = str((ctx or {}).get("thread_id") or "")
    if not tid: return
    declared: list[tuple[int, str, str]] = []
    for i, s in enumerate(input_.get("steps") or [], start=1):
        if not isinstance(s, dict): continue
        sk = (s.get("skill") or "").strip()
        if not sk: continue
        title = (s.get("title") or "").strip()
        declared.append((i, title, sk))
    if declared:
        _THREAD_DECLARED_RECIPES[tid] = declared
    elif tid in _THREAD_DECLARED_RECIPES:
        # New plan with no skill fields → clear stale bindings rather than leave them.
        del _THREAD_DECLARED_RECIPES[tid]


def rehydrate_declared_recipes(thread_id: str) -> list[tuple[int, str, str]]:
    """Read the thread's most recent plan entity's `metadata.plan.steps[]`
    and re-populate `_THREAD_DECLARED_RECIPES[tid]` from any `step.skill`
    bindings. Lossless: the hook above populates it at present_plan time,
    but the cache is in-process and gets wiped on bounce. Without this
    rebuild, every server restart silently drops the persistent
    "recipe rules" the agent declared — even though the plan entity
    itself survives. Observed in prj_1141348f 2026-06-19: the
    declared_recipes block stopped rendering after a bounce, so the
    agent kept the step titles but lost the recipe's thresholds/
    gotchas. Returns the populated list."""
    tid = str(thread_id or "")
    if not tid:
        return []
    if _THREAD_DECLARED_RECIPES.get(tid):
        return _THREAD_DECLARED_RECIPES[tid]
    try:
        from core.graph.entities import list_entities
        import json as _j
        plans = [
            e for e in list_entities(type_filter="plan",            # noqa: seam
                                      include_archived=False)
            if ((e.get("metadata") or {}).get("thread_id") == tid)
        ]
    except Exception:                                            # noqa: BLE001
        return []
    if not plans:
        return []
    plans.sort(key=lambda e: e.get("created_at") or "", reverse=True)
    md = plans[0].get("metadata") or {}
    steps = ((md.get("plan") or {}).get("steps")) or []
    out: list[tuple[int, str, str]] = []
    for s in steps:
        if not isinstance(s, dict):
            continue
        sk = (s.get("skill") or "").strip()
        if not sk:
            continue
        n = int(s.get("n") or len(out) + 1)
        title = (s.get("title") or "").strip()
        out.append((n, title, sk))
    if out:
        _THREAD_DECLARED_RECIPES[tid] = out
    return out


# ── Tool-lifecycle hook registration ──────────────────────────────────────────
# The guardrails above are registered into the in-process hook registry
# (core.runtime.hooks), which adopts the Claude Agent SDK's Pre/Post/PostFailure
# decision contract; _dispatch_tool just drives the registry. Imported here (not at
# top) so registration runs after the hook fns are defined. See misc/ SDK decision.
from core.runtime import hooks  # noqa: E402

hooks.pre_tool_use("run_python|run_r", label="preexec_veto")(_preexec_veto)
hooks.post_tool_use(label="recipe_uptake_hint")(_recipe_uptake_hint)
hooks.post_tool_use(label="fetch_fail_guardrail")(_fetch_fail_guardrail)
hooks.post_tool_use("fetch_url|lookup_sra_runinfo|fetch_ensembl", label="fetch_tool_failure_steer")(_fetch_tool_failure_steer)
hooks.post_tool_use(label="judgment_guardrails")(_judgment_guardrails)
hooks.post_tool_use("run_python|run_r", label="synth_taint_steer")(_synth_taint_steer)
hooks.post_tool_use("present_plan", label="capture_declared_recipes")(_capture_declared_recipes)


# ── Path-recovery guardrail (live diagnosis 2026-05-31) ─────────────────────
# When run_python/run_r fails with FileNotFoundError on a path whose BASENAME
# matches a known file in this thread (a prior run's artifact OR the thread's
# shared scratch), inject a corrective steer in the tool_result pointing at the
# actual absolute path. Soft-prompt steers about "use the preamble's absolute
# paths" lose to "I already had this pattern working last turn" — small models
# pattern-match prior successful code instead of re-reading directives. This
# hook fires AT THE FAILURE so the next turn has the right path AND the model
# sees concretely WHY the prior path was wrong.

_FILE_NOT_FOUND_RE = re.compile(
    r"FileNotFoundError:.*?'([^']+)'"
    r"|No such file or directory:\s*'([^']+)'"
    r"|cannot open file '([^']+)'"           # R wording
    r"|cannot find the file specified.*?'([^']+)'",
    re.IGNORECASE | re.DOTALL,
)


def _path_recovery_steer(name: str, input_: dict, result: dict, ctx: dict | None = None) -> None:
    """If a run_* cell hit FileNotFoundError on a path whose basename matches a
    file we know exists elsewhere in this thread, point the agent at the actual
    absolute path. Best-effort & idempotent — never blocks the result."""
    if name not in ("run_python", "run_r") or not isinstance(result, dict): return
    if result.get("returncode") in (0, None): return
    err = (result.get("stderr") or "") + "\n" + (result.get("stdout") or "")
    m = _FILE_NOT_FOUND_RE.search(err)
    if not m: return
    bad_path = next((g for g in m.groups() if g), "").strip()
    if not bad_path: return
    bad_name = bad_path.rsplit("/", 1)[-1] or bad_path
    if not bad_name: return

    project_id = (ctx or {}).get("project_id") or ""
    thread_id = str((ctx or {}).get("thread_id") or "")
    if not thread_id: return
    # Reuse the same walker as the cwd-shift preamble — it already enumerates
    # prior runs + the thread scratch with absolute paths.
    try:
        from core.graph.entities import list_entities
        from core.data.workspace import scratch_dir
        from pathlib import Path
        # Walk prior-run artifact_paths + thread-scratch (one level deep).
        candidates: list[Path] = []
        for e in reversed(list_entities(type_filter="analysis", include_archived=False)):
            md = e.get("metadata") or {}
            if md.get("thread_id") != thread_id: continue
            ap = e.get("artifact_path") or ""
            if not ap: continue
            p = Path(ap)
            if p.is_dir(): candidates.append(p)
        try:
            sp = scratch_dir(str(project_id or "default"), f"thread-{thread_id}")
            if sp.is_dir(): candidates.append(sp)
        except Exception: pass

        hits: list[str] = []
        for root in candidates:
            try:
                for entry in root.iterdir():
                    if entry.is_file() and entry.name == bad_name:
                        hits.append(str(entry))
                    elif entry.is_dir():
                        for inner in entry.iterdir():
                            if inner.is_file() and inner.name == bad_name:
                                hits.append(str(inner))
            except OSError:
                continue
            if hits: break          # closest match wins; don't enumerate every duplicate
        if not hits: return
        result["path_recovery_hint"] = (
            f"The path '{bad_path}' does not exist (FileNotFoundError). The file "
            f"`{bad_name}` exists in this thread at:\n"
            + "\n".join(f"  {h}" for h in hits[:3])
            + "\n\nLikely cause: a NEW Run was opened since you wrote this file, so the kernel "
              "cwd has shifted. Relative paths like `./geo_data/...` resolve against the CURRENT cwd, "
              "not the dir where you originally wrote the file. **Use the ABSOLUTE path above verbatim — "
              "do not concatenate `DATA_DIR/` or invent a parent dir.** DATA_DIR is for user uploads; "
              "files you downloaded yourself live in your previous WORK_DIR (the absolute path shown)."
        )
        # Also mirror into stdout so the model sees it without needing to read a custom field
        # (some models drop non-canonical tool-result keys).
        result["stdout"] = (result.get("stdout") or "") + "\n\n── path-recovery hint ──\n" + result["path_recovery_hint"] + "\n"
    except Exception:                # noqa: BLE001 — guardrail must not break the result
        return


hooks.post_tool_use("run_python|run_r", label="path_recovery_steer")(_path_recovery_steer)


# ── Multi-panel dashboard steer (live diagnosis 2026-05-31) ─────────────────
# scRNA-seq tutorial canon defaults to 2×2 dashboards (QC histograms, UMAP-by-
# variable). The soft prompt rule in figures.md loses to this training prior on
# small models. When the agent's cell creates a >=4-panel grid AND saves it as
# a figure, append a corrective steer for the NEXT turn — same lever as the
# path-recovery hook. We don't undo the current figure; we curb the next one.

_DASHBOARD_PATTERN_RE = re.compile(
    # plt.subplots(N, M) / subplots(N, M, …) where N*M ≥ 4 — the typical 2×2,
    # 2×3, 3×3 dashboards. Capture rows + cols.
    r"\bsubplots\(\s*(\d+)\s*,\s*(\d+)",
)
_DASHBOARD_KEYWORDS_RE = re.compile(
    r"\b(dashboard|executive\s+summary|comprehensive\s+(?:overview|summary)|"
    r"summary\s+(?:figure|dashboard|panel)|key\s+findings\s+panel|overview\s+figure)\b",
    re.IGNORECASE,
)


def _dashboard_pattern_steer(name: str, input_: dict, result: dict, ctx: dict | None = None) -> None:
    """If a run_* cell built a >=4-panel grid AND saved it, nudge the agent in the
    next turn toward single-panel figures. Heuristic: subplots(N, M) where N*M ≥ 4
    AND a `savefig`/`ggsave`/`png(` call exists in the same code. Best-effort;
    never breaks the result."""
    if name not in ("run_python", "run_r") or not isinstance(result, dict): return
    if result.get("returncode") not in (0, None): return        # only on success — failures have their own signal
    code = (input_ or {}).get("code", "") or ""
    if not code: return
    saved = bool(re.search(r"\bsavefig\(|\bggsave\(|\bpng\(|\bpdf\(", code))
    if not saved: return
    # (1) explicit dashboard keywords
    if _DASHBOARD_KEYWORDS_RE.search(code):
        _attach_dashboard_warning(result, reason="dashboard-keyword")
        return
    # (2) >=4-panel subplots grid
    for m in _DASHBOARD_PATTERN_RE.finditer(code):
        try:
            n_panels = int(m.group(1)) * int(m.group(2))
        except ValueError:
            continue
        if n_panels >= 4:
            _attach_dashboard_warning(result, reason=f"{m.group(1)}x{m.group(2)}-grid")
            return


def _attach_dashboard_warning(result: dict, *, reason: str) -> None:
    msg = (
        f"You just built a multi-panel figure ({reason}) + saved it. ONE PANEL PER FIGURE is "
        f"the default — multi-panel is justified ONLY for (a) explicit side-by-side comparison, "
        f"(b) panels that cross-reference each other, or (c) when the user asked for a composite. "
        f"For QC distributions (`n_genes`/`n_counts`/`pct_counts_mt`/etc.), UMAP-colored-by-variable, "
        f"or 'summary dashboards' — produce SEPARATE figures next time, ONE panel each. "
        f"(Tutorial canon defaults to grids; that's not what we want here.)"
    )
    result["figure_style_warning"] = msg
    result["stdout"] = (result.get("stdout") or "") + "\n\n── figure-style hint ──\n" + msg + "\n"


hooks.post_tool_use("run_python|run_r", label="dashboard_pattern_steer")(_dashboard_pattern_steer)


def _feedlog(msg: str) -> None:
    """Concise debug trace of every tool dispatch + hook event. Writes to BOTH the rolling
    /tmp/aba_turnlog/live.log (the file the turn-event logger writes — so it's all in one
    place to tail) AND backend stdout. On unless ABA_FEED_LOG=off."""
    if os.environ.get("ABA_FEED_LOG", "on").lower() == "off":
        return
    line = f"[feed] {msg}"
    print(line, flush=True)
    d = os.environ.get("ABA_TURN_LOG_DIR", "/tmp/aba_turnlog")
    if d.strip().lower() in ("", "off", "0", "false"):
        return
    try:
        import datetime as _dt
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "live.log"), "a") as f:
            f.write(f"{_dt.datetime.now().strftime('%H:%M:%S')} 🪝 {msg}\n")
    except Exception:  # noqa: BLE001 — never break the turn for a log write
        pass


def _summ_input(name, input_):
    i = input_ or {}
    if name in ("run_python", "run_r"):
        code = (i.get("code") or "").strip()
        head = code.splitlines()[0][:80] if code else ""
        return f"code[{len(code)}ch] {head!r}"
    if name == "present_plan":
        steps = i.get("steps") or i.get("plan") or []
        return f"title={i.get('title')!r} steps={len(steps) if isinstance(steps, list) else '?'}"
    return "{" + ", ".join(f"{k}={str(i[k])[:40]!r}" for k in list(i)[:3]) + "}"


def _summ_result(result):
    if not isinstance(result, dict):
        return str(result)[:60]
    flags = []
    for k in ("status", "returncode", "block_type", "reason_code", "entity_id", "run_id",
              "result_id", "rid", "recipe_hint", "fetch_warning"):
        if k in result:
            v = result[k]
            flags.append(f"{k}={v}" if isinstance(v, (int, bool)) else f"{k}={str(v)[:30]!r}")
    if result.get("guardrail_warnings"):
        flags.append(f"guardrail_warnings={len(result['guardrail_warnings'])}")
    return "{" + ", ".join(flags) + "}"


def _dispatch_tool(name: str, input_: dict, ctx: dict | None, inspect) -> str:
    # Phase 6.B+: a migrated tool lives on the in-process aba_core MCP
    # server. The agent still sees the bare name (TOOL_SCHEMAS hasn't
    # been pruned yet), so we route to MCP by name lookup. Failure on
    # the MCP route surfaces loudly — no fall-through to EXECUTORS, so
    # a bug in the aba_core handler is visible rather than masked.
    #
    # Phase 6.C: ctx propagation. Non-serializable runtime objects
    # (cancel_token, progress_q, kernel sess, etc.) can't cross the
    # MCP arg wire — we stash ctx in a thread-safe store and inject
    # an `aba_ctx_id` arg the handler uses to peek_ctx() back. Always
    # pop in the finally block so a crashed handler doesn't leak.
    try:
        from core.runtime.mcp import is_inprocess_tool, call as mcp_call
        if is_inprocess_tool(name):
            cancel_token = (ctx or {}).get("cancel_token")
            from core.runtime.tool_ctx import stash_ctx, pop_ctx
            cid = stash_ctx(ctx)
            _feedlog(f"TOOL {name} {_summ_input(name, input_)}  (route: aba_core)")
            try:
                decision, input_ = hooks.run_pre(name, input_, ctx)
                if decision is not None:
                    _feedlog(f"VETO {name} -> {decision.reason_code}")
                    return json.dumps(hooks.deny_to_result(decision))
                # Inject the ctx id so the handler can retrieve the
                # stashed ctx. Hidden field — TOOL_SCHEMAS doesn't
                # advertise it, so the model never sees it.
                args = {**(input_ or {})}
                if cid:
                    args["aba_ctx_id"] = cid
                wire = mcp_call(f"aba_core:{name}", args,
                                cancel_token=cancel_token)
                # The gateway returns {status, content, is_error};
                # `content` is the JSON-stringified tool result (FastMCP
                # serializes the dict return value as text content).
                # Parse it back so PostToolUse hooks see the real dict.
                if isinstance(wire, dict) and "content" in wire and not wire.get("is_error"):
                    try:
                        result = json.loads(wire["content"])
                    except Exception:  # noqa: BLE001
                        result = wire    # leave as wire shape if non-JSON
                else:
                    result = wire
                if isinstance(result, dict):
                    hooks.run_post(name, input_, result, ctx)
                _feedlog(f"DONE {name} -> {_summ_result(result)}")
                return json.dumps(result)
            except Exception as e:  # noqa: BLE001
                _feedlog(f"ERROR {name} (aba_core) -> {e}")
                return json.dumps({"error": str(e)})
            finally:
                pop_ctx(cid)
    except Exception:  # noqa: BLE001 — gateway import / lookup failed; let EXECUTORS handle it
        pass

    fn = EXECUTORS.get(name)
    if fn is None:
        # P3 #1 — try the MCP gateway for EXTERNAL servers ('server:tool').
        # Forward the cancel token so a Stop click can interrupt the call.
        try:
            from core.runtime.mcp import is_mcp_tool, call as mcp_call
            if is_mcp_tool(name):
                cancel_token = (ctx or {}).get("cancel_token")
                return json.dumps(mcp_call(name, input_ or {}, cancel_token=cancel_token))
        except Exception:  # noqa: BLE001
            pass    # fall through to unknown-tool error
        return json.dumps({"error": f"Unknown tool: {name}"})
    _feedlog(f"TOOL {name} {_summ_input(name, input_)}")
    try:
        # PreToolUse hooks (incl. the #305 veto): may block with a typed control-state
        # result (skip execution) or rewrite the input before fn() runs.
        decision, input_ = hooks.run_pre(name, input_, ctx)
        if decision is not None:
            _feedlog(f"VETO {name} -> {decision.reason_code}")
            return json.dumps(hooks.deny_to_result(decision))
        sig_params = inspect.signature(fn).parameters
        result = fn(input_, ctx) if "ctx" in sig_params else fn(input_)
        if isinstance(result, dict):
            # PostToolUse hooks (recipe-uptake nudge, fetch-fail detector, judgment
            # steers) + PostToolUseFailure hooks (fire only on a failure result).
            hooks.run_post(name, input_, result, ctx)
        _feedlog(f"DONE {name} -> {_summ_result(result)}")
        return json.dumps(result)
    except Exception as e:
        _feedlog(f"ERROR {name} -> {e}")
        return json.dumps({"error": str(e)})
