"""
Provenance walks over the entity_edges graph (arch §2.2, §3.4).

Edge direction convention (set in registry.py / promote.py):
  source --rel--> target, where the source is derived from / supported by /
  generated by the target. So:
    - upstream of X  = follow X's OUTGOING edges to their targets
    - downstream of X = follow INCOMING edges from their sources
"""
from __future__ import annotations
from core.graph.edges import edges_from, edges_to
from core.graph.entities import get_entity


def _node(entity_id: str) -> dict | None:
    e = get_entity(entity_id)
    if not e:
        return None
    return {"id": e["id"], "type": e["type"], "title": e["title"]}


def upstream(entity_id: str, max_depth: int = 3) -> list[dict]:
    """Entities this one was derived from, breadth-first, capped at depth."""
    seen: set[str] = {entity_id}
    out: list[dict] = []
    frontier = [(entity_id, 0)]
    while frontier:
        node_id, depth = frontier.pop(0)
        if depth >= max_depth:
            continue
        for edge in edges_from(node_id):
            tgt = edge["target_id"]
            if tgt in seen:
                continue
            seen.add(tgt)
            node = _node(tgt)
            if node:
                out.append({**node, "rel": edge["rel_type"], "depth": depth + 1})
                frontier.append((tgt, depth + 1))
    return out


def downstream(entity_id: str, max_depth: int = 3) -> list[dict]:
    """Entities that depend on this one (would need recompute if it changed)."""
    seen: set[str] = {entity_id}
    out: list[dict] = []
    frontier = [(entity_id, 0)]
    while frontier:
        node_id, depth = frontier.pop(0)
        if depth >= max_depth:
            continue
        for edge in edges_to(node_id):
            src = edge["source_id"]
            if src in seen:
                continue
            seen.add(src)
            node = _node(src)
            if node:
                out.append({**node, "rel": edge["rel_type"], "depth": depth + 1})
                frontier.append((src, depth + 1))
    return out


def _dedupe_titles(nodes: list[dict]) -> list[dict]:
    """Collapse the wasDerivedFrom + supports duplicate edges to one row per target."""
    seen: set[str] = set()
    out = []
    for n in nodes:
        if n["id"] in seen:
            continue
        seen.add(n["id"])
        out.append(n)
    return out


def provenance_text(entity_id: str, *, max_depth: int = 3) -> str:
    """Plain-English upstream description for the agent."""
    e = get_entity(entity_id)
    if not e:
        return "Entity not found."
    up = _dedupe_titles(upstream(entity_id, max_depth=max_depth))
    if not up:
        return f'"{e["title"]}" has no recorded upstream provenance.'
    lines = [f'"{e["title"]}" ({e["type"]}) was derived from:']
    for n in up:
        indent = "  " * n["depth"]
        lines.append(f'{indent}- {n["type"]} "{n["title"]}" (via {n["rel"]})')
    return "\n".join(lines)


def dependents_text(entity_id: str, *, max_depth: int = 3) -> str:
    """Plain-English downstream description for the agent."""
    e = get_entity(entity_id)
    if not e:
        return "Entity not found."
    down = _dedupe_titles(downstream(entity_id, max_depth=max_depth))
    if not down:
        return f'Nothing currently depends on "{e["title"]}".'
    lines = [f'If "{e["title"]}" changed, these would need to be reconsidered:']
    for n in down:
        indent = "  " * n["depth"]
        lines.append(f'{indent}- {n["type"]} "{n["title"]}" (via {n["rel"]})')
    return "\n".join(lines)


def neighborhood(entity_id: str, *, max_depth: int = 3) -> dict:
    """Structured upstream + downstream for the UI panel."""
    return {
        "upstream": _dedupe_titles(upstream(entity_id, max_depth=max_depth)),
        "downstream": _dedupe_titles(downstream(entity_id, max_depth=max_depth)),
    }
