"""Tier-0-tray icon assets: presence, dimensions, format.

Generated by ``install/mac/tray/icon-sources/build_icons.py`` — the script
is the source of truth, but these tests guard against drift (e.g. an
accidental commit of partial output, a missing iconset entry post-resize)
so the bundle template stays installable."""
from __future__ import annotations
import struct
from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parents[4]
RESOURCES = ROOT / "install" / "mac" / "tray" / "ABA.app" / "Contents" / "Resources"


def _png_dims(p: Path) -> tuple[int, int]:
    """Read the IHDR chunk of a PNG so we don't need Pillow at test time."""
    with p.open("rb") as f:
        sig = f.read(8)
        assert sig == b"\x89PNG\r\n\x1a\n", f"{p} is not a PNG"
        f.read(4)              # IHDR length
        assert f.read(4) == b"IHDR"
        w, h = struct.unpack(">II", f.read(8))
        return w, h


def test_app_icon_icns_is_present_and_nontrivial():
    icns = RESOURCES / "AppIcon.icns"
    assert icns.is_file(), (
        f"missing {icns}. Regenerate with `python install/mac/tray/"
        f"icon-sources/build_icons.py`.")
    # ICNS files have an 8-byte 'icns' magic header + 4-byte length.
    # A real iconset is several hundred KB; a corrupt empty one is < 1 KB.
    size = icns.stat().st_size
    assert size > 100_000, (
        f"AppIcon.icns is only {size} bytes — likely a partial render. "
        f"Re-run build_icons.py.")
    with icns.open("rb") as f:
        assert f.read(4) == b"icns", "AppIcon.icns missing icns magic header"


def test_tray_template_pngs_are_correct_size():
    one_x = RESOURCES / "TrayIconTemplate.png"
    two_x = RESOURCES / "TrayIconTemplate@2x.png"
    assert one_x.is_file() and two_x.is_file(), (
        f"missing tray template at {one_x} / {two_x}")
    # Menu-bar convention: 22pt base, 44px at 2x.
    assert _png_dims(one_x) == (22, 22), (
        f"TrayIconTemplate.png should be 22x22, got {_png_dims(one_x)}")
    assert _png_dims(two_x) == (44, 44), (
        f"TrayIconTemplate@2x.png should be 44x44, got {_png_dims(two_x)}")


def test_tray_template_filename_ends_with_Template():
    """Apple convention: NSImage auto-tints any image whose filename ends
    with 'Template' (e.g. via `setTemplate:YES`). We use this rather than
    setting the flag at runtime so rumps + AppKit do the right thing
    without extra wiring."""
    names = [p.name for p in RESOURCES.glob("TrayIcon*")]
    assert any(n.startswith("TrayIcon") and "Template" in n for n in names), (
        f"no Template-suffixed tray image in {RESOURCES}: {names}. Without "
        f"the 'Template' suffix, macOS won't auto-tint the glyph for the "
        f"menu-bar's foreground colour.")


def test_iconset_scratch_dir_has_all_sizes():
    """The .iconset directory is what iconutil consumed. Keep it around
    (build_icons.py doesn't clean it) for human preview / re-encoding,
    and verify it's complete so a future re-run of iconutil from CI
    doesn't get a partial set."""
    iconset = ROOT / "install" / "mac" / "tray" / "icon-sources" / "AppIcon.iconset"
    if not iconset.exists():
        pytest.skip("iconset scratch dir cleaned away — that's fine, the "
                    "compiled AppIcon.icns is the real artifact")
    expected = {
        "icon_16x16.png", "icon_16x16@2x.png",
        "icon_32x32.png", "icon_32x32@2x.png",
        "icon_128x128.png", "icon_128x128@2x.png",
        "icon_256x256.png", "icon_256x256@2x.png",
        "icon_512x512.png", "icon_512x512@2x.png",
    }
    have = {p.name for p in iconset.glob("*.png")}
    missing = expected - have
    assert not missing, f"iconset missing: {sorted(missing)}"
