"""Project-tier data store: resolve / register / promote / version.

The membrane verbs (data.md §6). P0 implements the project tier only:

- `register` is **store-by-reference** — it records where a file already is
  plus its lineage; it does not copy bytes into a content-addressed blob.
- `resolve` of a project handle is a lookup returning that path (no staging).
- `promote` flips scope (no byte movement until the reference CAS exists, P4).

`resolve`/`register` are *opt-in*: ad-hoc code in the sandbox reads/writes
workspace files by plain path and never calls them. They become load-bearing
on the capability surface (P2) and for references (P4).
"""
from __future__ import annotations
import os
from typing import Optional, Union

from core.data.handles import DataHandle, ExecContext, StagedInput
from core.graph.entities import create_entity, get_entity, update_entity
from core.graph.edges import add_edge

# A lineage spec maps a PROV-O rel type to one or more target entity IDs.
#   {"wasDerivedFrom": ["ds_01"], "wasGeneratedBy": "run_17", "used": [...]}
Lineage = dict[str, Union[str, list[str]]]

DEFAULT_SCOPE = "project"


def _scope_of(entity: dict) -> str:
    meta = entity.get("metadata") or {}
    return meta.get("scope", DEFAULT_SCOPE)


def resolve(handle: DataHandle, ctx: Optional[ExecContext] = None) -> StagedInput:
    """Stage a handle to a locally-readable path.

    P0 / project tier: look up the entity, return its existing path and a
    version lock. `ctx` is accepted (frozen signature) but unused while the
    only location is "local" and the only tier is the project store — there is
    nothing to stage. The reference tier (P4) adds mount/download/sign here.
    """
    entity = get_entity(handle.entity_id)
    if entity is None:
        raise KeyError(f"cannot resolve unknown entity: {handle.entity_id}")
    path = entity.get("artifact_path")
    if not path:
        raise ValueError(
            f"entity {handle.entity_id} has no artifact_path to resolve "
            f"(type={entity.get('type')})"
        )
    # References are content-addressed: lock to their content sha so a run
    # records exactly which version it read. Other entities lock to updated_at.
    meta = entity.get("metadata") or {}
    lock = handle.version or meta.get("sha") or entity.get("updated_at") or "v0"
    return StagedInput(local_path=str(path), version_lock=str(lock))


def register(
    path: str,
    *,
    kind: str,
    lineage: Optional[Lineage] = None,
    scope: str = DEFAULT_SCOPE,
    title: Optional[str] = None,
    producing_params: Optional[dict] = None,
    parent_entity_id: Optional[str] = None,
) -> str:
    """Promote a (scratch) file to a tracked artifact entity, store-by-reference.

    Records the path + scope + lineage; the bytes stay where they are. Returns
    the new entity id. `lineage` edges are written source(new entity) --rel-->
    target, matching the provenance convention (the new entity was *derived
    from* / *generated by* / *used* its targets).

    Post Cutover 4: code provenance lives in exec records, not on the
    entity row. Callers that have an exec_id available should set it
    via update_entity(eid, exec_id=...) after registration.
    """
    from core.graph.derivation import from_lineage, imported
    meta = {"scope": scope}
    eid = create_entity(
        entity_type=kind,
        title=title or os.path.basename(str(path)) or kind,
        artifact_path=str(path),
        producing_params=producing_params,
        parent_entity_id=parent_entity_id,
        # Phase 2B: derived_from the lineage targets, else imported (registered file).
        derivation=from_lineage(lineage, imported(os.path.basename(str(path)) or kind)),
        metadata=meta,
    )
    for rel, targets in (lineage or {}).items():
        for target_id in ([targets] if isinstance(targets, str) else targets):
            add_edge(eid, target_id, rel)
    return eid


def promote(entity_id: str, to_scope: str) -> str:
    """Elevate a project artifact to a broader scope.

    P0 stub: flip the scope tag. No byte movement — the content-addressed
    shared-reference tier (which would hash + place the bytes) arrives in P4,
    behind this same signature.
    """
    entity = get_entity(entity_id)
    if entity is None:
        raise KeyError(f"cannot promote unknown entity: {entity_id}")
    meta = dict(entity.get("metadata") or {})
    meta["scope"] = to_scope
    update_entity(entity_id, metadata=meta)
    return entity_id


def version(entity_id: str, *, path: Optional[str] = None) -> str:
    """Record a new version of a tracked entity; returns the version lock.

    P0: a thin lock-token bump (optionally repointing the path). The full
    supersede-chain history is `core.graph.figure_history`'s job; this just
    advances `updated_at` so resolve() records a fresh lock.
    """
    fields: dict = {}
    if path is not None:
        fields["artifact_path"] = str(path)
    updated = update_entity(entity_id, **fields)
    if updated is None:
        raise KeyError(f"cannot version unknown entity: {entity_id}")
    return str(updated.get("updated_at") or "v0")
