/**
 * Result (kept observation) view. A Result is a *grouping*: one editable
 * "reading" (interpretation) plus an ordered list of member panels — figures,
 * tables, values, and text notes. The single-member case (the common one)
 * renders as a near-bare cell. Results grow deliberately: + Add panel pulls a
 * recent figure from this thread; + Note adds inline prose. Members are sections
 * of this one page — never separate destinations.
 */
import { useEffect, useLayoutEffect, useRef, useState } from 'react'
import type { Entity, ResultMember } from '../types'
import { EntityGlyph, AgentGlyph } from '../components/icons'
import RevisionStrip, { useFigureRevisions, type RevisionAction } from './RevisionStrip'
import ProvenanceSection from '../components/ProvenanceSection'
import ConfirmDialog from '../components/ConfirmDialog'
import { HILITE, captureHighlight, nextAnnotToken, type Pt } from '../components/highlightTools'
import './ResultView.css'


/** Label one of ResultView's "subcards" (cell-image, caption, note) for the
 *  agent-facing note. Mirror of describeSubcardDefault in highlightTools
 *  but tuned to the rv-panel class names. */
function _rvDescribeSubcard(sc: HTMLElement): string {
  if (sc.classList.contains('rv-panel__cell')) {
    const img = sc.querySelector('img') as HTMLImageElement | null
    const alt = img?.getAttribute('alt')?.trim()
    return alt ? `figure "${alt}"` : 'the figure'
  }
  if (sc.classList.contains('rv-panel__caption')) {
    const txt = ((sc as HTMLTextAreaElement).value || sc.textContent || '').trim().slice(0, 80)
    return txt ? `caption "${txt}${txt.length >= 80 ? '…' : ''}"` : 'the caption'
  }
  if (sc.classList.contains('rv-panel__note')) {
    const txt = ((sc as HTMLTextAreaElement).value || sc.textContent || '').trim().slice(0, 80)
    return txt ? `note "${txt}${txt.length >= 80 ? '…' : ''}"` : 'the note'
  }
  if (sc.classList.contains('rv-panel__table')) {
    return `table "${sc.textContent?.trim() ?? ''}"`
  }
  return ''
}

// A member is "non-autogenerated" (i.e. carries user-meaningful content)
// when it's a pinned figure or table, or a text note with non-empty text.
// Empty text notes are placeholder shells we treat as auto / disposable.
// Used to decide whether removing this member would leave the Result
// substantively empty (→ "use ⋯ menu to delete the Result" guard).
function _memberIsNonAuto(m: ResultMember): boolean {
  if (m.kind === 'figure' || m.kind === 'table') return true
  if (m.kind === 'text') return (m.text ?? '').trim().length > 0
  return false
}
function _isLastNonAutoMember(all: ResultMember[], m: ResultMember): boolean {
  if (!_memberIsNonAuto(m)) return false
  return all.filter(_memberIsNonAuto).length === 1
}

// Friendly download-chip label for a non-raster canonical. ".pdf" →
// "PDF"; falls back to the bare extension uppercased so SVG/EPS/etc.
// pick up a sensible label without us having to enumerate.
function _canonicalKindLabel(url: string | null | undefined): string {
  if (!url) return 'Original'
  const m = /\.([a-z0-9]{1,5})(?:\?|$)/i.exec(url)
  if (!m) return 'Original'
  return m[1].toUpperCase()
}

const IMG = /\.(png|jpe?g|svg|webp|gif)$/i

export default function ResultView({ result, entities, onChange, onFocus, onAsk, onChatResult,
                                     onAnnotate, annotClear, hlOwner, highlighting: highlightingProp,
                                     onHighlightingChange }: {
  result: Entity
  entities: Entity[]
  onChange: () => void
  onFocus: (id: string) => void
  onAsk?: (t: string) => void
  onChatResult?: (label: string, thumb?: string,
                  annotation?: { image: string; note: string },
                  action?: 'chat' | 'revision' | 'revision-supersede' | 'reproduce',
                  entityId?: string) => void
  /** Capture-handoff for the freehand Highlight tool — sends {image, note}
   *  to the composer (App.tsx:attachAnnotation). When undefined the toggle
   *  hides itself. */
  onAnnotate?: (a: { image: string; note: string }, ownerId?: string) => void
  /** Bumped on focus change / annotation clear; signals MemberPanels to
   *  drop any in-progress stroke. */
  annotClear?: number
  /** Token of the panel that currently owns the pinned highlight (App state).
   *  A MemberPanel keeps its captured mark frozen only while it holds this. */
  hlOwner?: string | null
  /** Highlight mode (lifted from App.tsx so the canvas-actions ✏️ button
   *  drives this view's MemberPanels). Provided when ResultView is hosted
   *  inside FocusCanvas; falls back to local state for standalone tests. */
  highlighting?: boolean
  onHighlightingChange?: (on: boolean) => void
}) {
  const members = (result.metadata?.members as ResultMember[]) ?? []
  const interpretation = (result.metadata?.interpretation as string) ?? ''
  const interpOrigin = (result.metadata?.interpretation_origin as string) ?? ''
  const titleOrigin = (result.metadata?.title_origin as string) ?? ''
  const threadId = result.metadata?.thread_id as string | undefined
  const cellById = (id?: string) => (id ? entities.find(e => e.id === id) : undefined)

  const [titleEdit, setTitleEdit] = useState(false)
  const [title, setTitle] = useState(result.title)
  const [reading, setReading] = useState(interpretation)
  const [synthesisOpen, setSynthesisOpen] = useState(false)
  const [synthGen, setSynthGen] = useState(false)          // synthesis being generated
  const lastSyncedInterp = useRef(interpretation)
  const [picker, setPicker] = useState(false)
  const [zoom, setZoom] = useState<string | null>(null)
  const [focusMember, setFocusMember] = useState<string | null>(null)
  // Multi-member viewport pick: which panel the user has scrolled into
  // view. Used to surface a focus_member_id with the next chat send so
  // the agent's Result focus card marks the right panel for "this
  // plot" gestures. Suppressed entirely when the Result has ≤ 1 major
  // member (the visual cue + the signal both vanish — there's nothing
  // to disambiguate).
  const [activeMemberId, setActiveMemberId] = useState<string | null>(null)
  const membersRef = useRef<HTMLDivElement | null>(null)
  // Count panels for the gate. Every member kind is considered "major"
  // — figures, tables, and text notes all render as their own panel
  // and so deserve disambiguation when more than one is present.
  const trackFocus = members.length > 1
  // Freehand-highlight mode. When the prop is wired (i.e. mounted inside
  // FocusCanvas), use the external state — the canvas-actions row's ✏️
  // button is the single toggle. When undefined (standalone tests), fall
  // back to local state. anyDrawing is the global "someone's currently
  // dragging" flag so OTHER panels hide their surface during the drag.
  const [hlLocal, setHlLocal] = useState(false)
  const highlighting = highlightingProp ?? hlLocal
  const setHighlighting = (on: boolean) => (onHighlightingChange ?? setHlLocal)(on)
  const [anyDrawing, setAnyDrawing] = useState(false)
  // Text-selection → "Claim from selection": the trimmed text + a screen
  // position for the floating pill (mirrors ChatPane's `sel`).
  const [sel, setSel] = useState<{ text: string; x: number; y: number } | null>(null)
  // Exit highlight mode when the focused entity changes or the parent
  // signals an annotation-clear (avoids stale ✏️-on state after Esc).
  useEffect(() => { setHighlighting(false) }, [result.id, annotClear])  // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => { setReading(interpretation); setTitle(result.title); lastSyncedInterp.current = interpretation }, [result.id]) // eslint-disable-line react-hooks/exhaustive-deps

  // Pick up a background-generated synthesis (auto at pin, or the Guide button via
  // the entity_updated broadcast) WITHOUT clobbering an in-flight user edit — mirrors
  // the caption sync in MemberPanel.
  useEffect(() => {
    setReading(prev => {
      if (prev === lastSyncedInterp.current) { lastSyncedInterp.current = interpretation; return interpretation }
      if (prev === interpretation) { lastSyncedInterp.current = interpretation; return prev }
      return prev   // user has an unsaved edit → keep it
    })
  }, [interpretation])

  // Auto-resize the Result-level synthesis textarea (rarely used, but if
  // the user writes one we let it grow with the content like the figure
  // captions do).
  const readingRef = useRef<HTMLTextAreaElement>(null)
  useLayoutEffect(() => {
    const el = readingRef.current
    if (!el) return
    el.style.height = 'auto'
    el.style.height = el.scrollHeight + 'px'
  }, [reading])
  useEffect(() => {
    if (!zoom) return
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') setZoom(null) }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [zoom])

  // Text-selection → "Claim from selection" (mirrors ChatPane): selecting a
  // span inside the members body surfaces a floating pill that drafts a claim
  // citing THIS result as evidence. Scoped to membersRef so a selection made
  // elsewhere on the page is ignored; ≥ 8 chars filters stray clicks/drags.
  useEffect(() => {
    function onUp() {
      const s = window.getSelection()
      const text = s?.toString().trim() ?? ''
      const node = s && s.rangeCount ? s.anchorNode : null
      const host = node?.nodeType === 3 ? node.parentElement : (node as Element | null)
      if (!text || text.length < 8 || !host || !membersRef.current?.contains(host)) { setSel(null); return }
      const r = s!.getRangeAt(0).getBoundingClientRect()
      setSel({ text, x: r.left + r.width / 2, y: r.top })
    }
    document.addEventListener('mouseup', onUp)
    return () => document.removeEventListener('mouseup', onUp)
  }, [])

  // ── Multi-member viewport tracking ──────────────────────────────────────
  // Gated on members.length > 1: a one-panel Result has nothing to
  // disambiguate, so we don't pay observer cost and don't render a
  // border. When tracking IS active, an IntersectionObserver keeps a
  // per-panel visibility ratio map up to date as the user scrolls;
  // a small computation picks the most-visible panel as the active
  // one. The pick is NOT triggered by hover or mouse movement — only
  // by intersection changes — so the border stays put when the user
  // moves to the chat box to type, matching the "looks at" reading.
  useEffect(() => {
    setActiveMemberId(null)
    if (!trackFocus) {
      // Clear the module-level ref so a previous result's pick can't
      // leak into a single-member result's first message.
      import('./activeMemberRef').then(m => m.clearActiveMember(result.id))
      return
    }
    const container = membersRef.current
    if (!container) return
    const panels = Array.from(
      container.querySelectorAll<HTMLElement>('[data-member-id]')
    )
    if (panels.length === 0) return
    const visibility = new Map<string, number>()
    // Seed with the topmost panel so the first user message before any
    // scroll has a non-null pick (matches "I just opened this Result
    // and asked about the first panel without scrolling").
    const firstId = panels[0].getAttribute('data-member-id') || ''
    if (firstId) setActiveMemberId(firstId)

    type Best = { id: string; ratio: number; domOrder: number }
    const recompute = () => {
      let best: Best | null = null
      panels.forEach((p, i) => {
        const id = p.getAttribute('data-member-id') || ''
        if (!id) return
        const ratio = visibility.get(id) ?? 0
        const cur: Best = { id, ratio, domOrder: i }
        if (!best
            || cur.ratio > best.ratio
            || (cur.ratio === best.ratio && cur.domOrder < best.domOrder)) {
          best = cur
        }
      })
      const winner = best as Best | null
      if (winner && winner.ratio > 0) setActiveMemberId(winner.id)
    }

    // Debounce the visual pick: the cosmetic border should only update
    // when scrolling settles, not on every visibility-ratio frame.
    // Otherwise the dashed outline flickers between panels during the
    // scroll itself, which the user reads as "weird, follows page
    // position". Send-time correctness is unaffected — useChat reads
    // the module ref directly when the user presses send.
    let timer: number | null = null
    const scheduleRecompute = () => {
      if (timer != null) window.clearTimeout(timer)
      timer = window.setTimeout(() => { timer = null; recompute() }, 220)
    }

    const io = new IntersectionObserver(
      entries => {
        for (const e of entries) {
          const id = (e.target as HTMLElement).getAttribute('data-member-id') || ''
          if (!id) continue
          visibility.set(id, e.intersectionRatio)
        }
        scheduleRecompute()
      },
      { threshold: [0, 0.1, 0.25, 0.5, 0.75, 1.0] },
    )
    panels.forEach(p => io.observe(p))
    return () => {
      if (timer != null) window.clearTimeout(timer)
      io.disconnect()
    }
  }, [trackFocus, result.id, members.length])

  // Sync the local active-member state into the module-level ref so
  // useChat can read it at chat-send time without prop drilling.
  useEffect(() => {
    let cancelled = false
    import('./activeMemberRef').then(m => {
      if (cancelled) return
      if (trackFocus && activeMemberId) {
        m.setActiveMember(result.id, activeMemberId)
      } else {
        // No tracking, OR tracking but no pick yet — clear the slot for
        // this result id so a stale pick doesn't leak.
        m.clearActiveMember(result.id)
      }
    })
    return () => { cancelled = true }
  }, [trackFocus, activeMemberId, result.id])

  // Drop the recorded pick when this ResultView unmounts (focus moved
  // away). The result-id-gated getter in useChat would already refuse
  // a stale id, but clearing on unmount keeps the module ref tidy.
  useEffect(() => {
    const rid = result.id
    return () => {
      import('./activeMemberRef').then(m => m.clearActiveMember(rid))
    }
  }, [result.id])

  async function api(path: string, method = 'POST', body?: unknown) {
    await fetch(path, {
      method,
      headers: body ? { 'Content-Type': 'application/json' } : undefined,
      body: body ? JSON.stringify(body) : undefined,
    }).catch(() => {})
    onChange()
  }
  const rid = encodeURIComponent(result.id)
  const saveTitle = () => { setTitleEdit(false); if (title.trim() && title.trim() !== result.title) api(`/api/entities/${rid}`, 'PATCH', { title: title.trim() }) }
  // On any user edit, flip interpretation_origin to 'user' so the ✨ tag disappears
  // and the background auto-interpret won't overwrite the user's text later.
  const saveReading = () => {
    if (reading !== interpretation)
      api(`/api/entities/${rid}`, 'PATCH', { interpretation: reading, interpretation_origin: 'user' })
  }
  // Green-star Guide button: generate (or re-generate) the synthesis across panels.
  // Async — the field shows a "generating…" status while it runs.
  const generateSynthesis = async () => {
    if (synthGen) return
    setSynthGen(true); setSynthesisOpen(true)
    try {
      const r = await fetch(`/api/results/${rid}/synthesize`, { method: 'POST' })
      if (r.ok) {
        const d = await r.json()
        if (d.interpretation) { setReading(d.interpretation); lastSyncedInterp.current = d.interpretation }
      }
    } catch { /* leave the field as-is on failure */ } finally { setSynthGen(false) }
  }
  const addFigure = (cellId: string) => { setPicker(false); api(`/api/results/${rid}/members`, 'POST', { kind: 'figure', ref: cellId }) }
  const addNote = async () => {
    const r = await fetch(`/api/results/${rid}/members`, {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ kind: 'text', text: '' }),
    }).catch(() => null)
    if (r && r.ok) {
      const res = await r.json()
      const ms = (res.metadata?.members as ResultMember[]) ?? []
      setFocusMember(ms[ms.length - 1]?.id ?? null)  // autofocus the new note
    }
    onChange()
  }
  // + Upload evidence: send a file straight into THIS Result as a new member.
  // The Result's interpretation is NOT regenerated — the description belongs to
  // the Result as a whole; new evidence rides under it.
  const uploadRef = useRef<HTMLInputElement>(null)
  const uploadEvidence = async (file: File) => {
    const fd = new FormData(); fd.append('file', file)
    await fetch(`/api/results/${rid}/upload-evidence`, { method: 'POST', body: fd }).catch(() => {})
    onChange()
  }
  // Make a claim citing THIS result as evidence, then open it entity-first for
  // review/edit (mirrors App.createClaim + FocusCanvas.doFigureClaim). Shared by
  // the text-selection pill and the "Make new Claim" button in the add-row.
  const makeClaim = async (statement: string) => {
    const r = await fetch('/api/claims', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ statement, evidence_ids: [result.id], thread_id: threadId }),
    }).catch(() => null)
    if (r && r.ok) { const c = await r.json(); onChange(); onFocus(c.id) }
  }
  const removeMember = (mid: string) => api(`/api/results/${rid}/members/${encodeURIComponent(mid)}`, 'DELETE')
  // Hard-delete one revision in a figure/table chain. The backend re-parents
  // children and re-anchors member.ref so the chain stays navigable. Refuses
  // on the only active version (UI gates that via chain length).
  const deleteRevision = async (entityId: string) => {
    const r = await fetch(`/api/entities/${encodeURIComponent(entityId)}/delete-revision`, { method: 'POST' })
    if (!r.ok) { console.error('delete-revision failed', r.status, await r.text()); return }
    onChange()
  }
  const saveCaption = (mid: string, caption: string, origin: 'user' = 'user') =>
    api(`/api/results/${rid}/members/${encodeURIComponent(mid)}`, 'PATCH', { caption, caption_origin: origin })
  const saveText = (mid: string, text: string) => api(`/api/results/${rid}/members/${encodeURIComponent(mid)}`, 'PATCH', { text })
  const move = (idx: number, dir: -1 | 1) => {
    const ids = members.map(m => m.id)
    const j = idx + dir
    if (j < 0 || j >= ids.length) return
    ;[ids[idx], ids[j]] = [ids[j], ids[idx]]
    api(`/api/results/${rid}/reorder`, 'POST', { order: ids })
  }

  const memberRefs = new Set(members.map(m => m.ref).filter(Boolean))
  const candidates = entities.filter(e =>
    e.type === 'figure' && e.artifact_path && IMG.test(e.artifact_path)
    && e.metadata?.thread_id === threadId && !memberRefs.has(e.id) && e.status !== 'archived')

  // Signal to RevisionStrip: when a new revision is added to ANY chain in
  // the project (the agent's make_revision broadcasts entity_updated →
  // App.refresh() → entities array updates), this count bumps and every
  // MemberPanel's useFigureHistory re-fetches its chain. Counts figures +
  // tables whose metadata.revision_of is set, i.e. any entity that is
  // itself a revision of something. Cheap (entity list length is bounded
  // per project) and inclusive (a revision anywhere in the chain bumps it).
  const revisionsSignal = entities.filter(e =>
    (e.type === 'figure' || e.type === 'table') &&
    Boolean((e.metadata as { revision_of?: string } | undefined)?.revision_of)
  ).length

  // Capture-then-attach. On a successful highlight, exit the mode (mirror
  // ChatPane: one mark, one attach, then return to normal interaction).
  const onPanelAnnotate = (a: { image: string; note: string }, ownerId?: string) => {
    onAnnotate?.(a, ownerId)
    setHighlighting(false)
    setAnyDrawing(false)
  }

  return (
    <div className="rv">
      {sel && (
        <button className="rv-claim-sel" style={{ left: Math.max(90, sel.x), top: Math.max(56, sel.y - 38) }}
          onMouseDown={e => e.preventDefault()}
          onClick={() => { makeClaim(sel.text); window.getSelection()?.removeAllRanges(); setSel(null) }}>
          ✦ Claim from selection
        </button>
      )}
      {/* Title row. The Highlight toggle now lives in App.tsx's
          canvas-actions row (consistent with the Threads view), so it's
          NOT rendered here — each MemberPanel is driven by the lifted
          `highlighting` prop. */}
      {titleEdit ? (
        <input className="rv__title-input" autoFocus value={title}
               onChange={e => setTitle(e.target.value)} onBlur={saveTitle}
               onKeyDown={e => { if (e.key === 'Enter') saveTitle(); if (e.key === 'Escape') { setTitle(result.title); setTitleEdit(false) } }} />
      ) : (
        <div className="rv__title-row">
          <h1 className="rv__title" onClick={() => setTitleEdit(true)} title="Click to rename">{result.title}</h1>
          {titleOrigin === 'ai' && (
            <span className="rv__ai-tag" title="Title suggested by Guide — edit to make it yours">
              <AgentGlyph agent="guide" size={13} />
            </span>
          )}
        </div>
      )}

      <div className="rv__members" ref={membersRef}>
        {members.map((m, i) => (
          <MemberPanel key={m.id} member={m} idx={i} count={members.length}
            cell={cellById(m.ref)} autoFocus={m.id === focusMember} onZoom={setZoom} onRemove={removeMember} onMove={move}
            onCaption={saveCaption} onText={saveText} onFocus={onFocus}
            onChatResult={onChatResult}
            onAsk={onAsk}
            onDeleteRevision={deleteRevision}
            resultTitle={result.title}
            isLastNonAutoMember={_isLastNonAutoMember(members, m)}
            revisionsSignal={revisionsSignal}
            highlighting={highlighting}
            anyDrawing={anyDrawing}
            onDrawingChange={setAnyDrawing}
            onAnnotate={onPanelAnnotate}
            hlOwner={hlOwner}
            entities={entities}
            isActive={trackFocus && m.id === activeMemberId} />
        ))}
        {members.length === 0 && <div className="rv__empty">Empty result — add a panel or a note below.</div>}
      </div>

      {/* Result-level synthesis across panels. Auto-generated at pin time (when
          the agent's context is richest) and via the Guide button below
          (generate / re-generate). AI-authored text carries the green Guide
          glyph, which clears on the first user edit. The figure caption lives on
          the MEMBER; this is the cross-panel take-home. */}
      {(reading.trim() || synthesisOpen || synthGen) ? (
        <div className="rv__synth">
          <div className="rv__synth-field">
            <textarea ref={readingRef} className="rv__reading" value={reading} disabled={synthGen}
                      placeholder={synthGen ? 'Generating synthesis…' : 'Synthesis across panels (optional)…'}
                      onChange={e => setReading(e.target.value)} onBlur={saveReading} rows={1} />
            {interpOrigin === 'ai' && !synthGen && reading.trim() && (
              <span className="rv__ai-tag rv__ai-tag--field" title="Synthesis suggested by Guide — edit to make it yours">
                <AgentGlyph agent="guide" size={13} />
              </span>
            )}
          </div>
          <button className="rv__synth-gen" onClick={generateSynthesis} disabled={synthGen}>
            <AgentGlyph agent="guide" size={13} />
            {synthGen ? 'Generating synthesis…' : reading.trim() ? 'Re-generate synthesis' : 'Generate synthesis'}
          </button>
        </div>
      ) : (
        <div className="rv__synth-empty">
          <button className="rv__add-synthesis" onClick={() => setSynthesisOpen(true)}>
            + Add a synthesis across panels (optional)
          </button>
          <button className="rv__synth-gen" onClick={generateSynthesis} disabled={synthGen}>
            <AgentGlyph agent="guide" size={13} />
            {synthGen ? 'Generating synthesis…' : 'Generate synthesis'}
          </button>
        </div>
      )}

      <div className="rv__add">
        <div className="rv__add-row">
          <button className="rv__add-btn" onClick={() => setPicker(p => !p)}>＋ Add panel</button>
          <button className="rv__add-btn" onClick={addNote}>＋ Note</button>
          <button className="rv__add-btn" onClick={() => uploadRef.current?.click()}>＋ Upload evidence</button>
          <input ref={uploadRef} type="file" style={{ display: 'none' }}
                 accept="image/*,.csv,.tsv,.xlsx,.pdf"
                 onChange={e => { const f = e.target.files?.[0]; if (f) uploadEvidence(f); e.target.value = '' }} />
          <button className="rv__add-btn rv__add-btn--claim"
                  title="Draft a claim supported by this result — edit it in the claim view"
                  onClick={() => makeClaim(reading.trim() || result.title)}>✦ Make new Claim</button>
        </div>
        {picker && (
          <div className="rv__picker">
            <div className="rv__picker-head">Recent figures in this thread</div>
            {candidates.length === 0 && <div className="rv__picker-empty">No unused figures in this thread. Ask the Guide to make one, or pin one from chat.</div>}
            <div className="rv__picker-grid">
              {candidates.map(c => (
                <button key={c.id} className="rv__picker-cell" title={c.title} onClick={() => addFigure(c.id)}>
                  <img src={c.artifact_path!} alt={c.title} />
                  <span>{c.title}</span>
                </button>
              ))}
            </div>
            {onAsk && (
              <button className="rv__picker-ask" onClick={() => { setPicker(false); onAsk(`Make a panel for the result "${result.title}": `) }}>
                ✦ Ask Guide to make one…
              </button>
            )}
          </div>
        )}
      </div>

      {zoom && (
        <div className="rv__zoom" onClick={() => setZoom(null)}>
          {/* Same inline-flex frame the chat lightbox uses so the X sits
              above the image's top-right corner instead of in the
              viewport's corner. */}
          <div className="rv__zoom-frame" onClick={e => e.stopPropagation()}>
            <button className="rv__zoom-x" onClick={() => setZoom(null)} aria-label="Close">×</button>
            <img src={zoom} />
          </div>
        </div>
      )}
    </div>
  )
}

function MemberPanel({ member, idx, count, cell, autoFocus, onZoom, onRemove, onMove, onCaption, onText, onFocus, onChatResult, onAsk, onDeleteRevision, resultTitle, isLastNonAutoMember, revisionsSignal,
                       highlighting, anyDrawing, onDrawingChange, onAnnotate, hlOwner, entities,
                       isActive }: {
  member: ResultMember
  idx: number
  count: number
  cell?: Entity
  autoFocus?: boolean
  onZoom: (url: string) => void
  onRemove: (mid: string) => void
  onMove: (idx: number, dir: -1 | 1) => void
  onCaption: (mid: string, caption: string, origin: 'user') => void
  onText: (mid: string, text: string) => void
  onFocus: (id: string) => void
  onChatResult?: (label: string, thumb?: string,
                  annotation?: { image: string; note: string },
                  action?: 'chat' | 'revision' | 'revision-supersede' | 'reproduce',
                  entityId?: string) => void
  onAsk?: (t: string) => void
  /** Hard-delete a single revision of a figure/table member's chain.
   *  See ResultView.tsx:deleteRevision for the HTTP wiring. */
  onDeleteRevision?: (entityId: string) => void
  resultTitle: string
  /** True if removing this member would leave the Result with no other
   *  user-meaningful members. The × triggers a different dialog in that
   *  case — directing the user to the ⋯ menu to delete the Result. */
  isLastNonAutoMember: boolean
  /** Bump-counter from the parent: when the project's entities array
   *  reports a new revision, this changes, and the chain is re-fetched.
   *  Without it the agent's background make_revision would leave the
   *  chevrons stale until a manual page reload. */
  revisionsSignal: number
  /** Global highlight mode (ResultView header toggle). */
  highlighting?: boolean
  /** Global "a panel is currently mid-drag" flag — suppresses surfaces on
   *  other panels so the stroke locks to this one for the duration. */
  anyDrawing?: boolean
  onDrawingChange?: (b: boolean) => void
  /** Capture-handoff: rasterized cell + structured note → composer. `ownerId`
   *  (a fresh token per capture) lets App track which panel owns the pinned
   *  mark so this panel can keep its overlay frozen until dismissed. */
  onAnnotate?: (a: { image: string; note: string }, ownerId?: string) => void
  /** Token of the panel that owns the pinned highlight (App state); this panel
   *  shows its frozen mark only while hlOwner === its own capture token. */
  hlOwner?: string | null
  /** Project entities (for figure-entity lookup inside describeHighlightedFigure). */
  entities?: Entity[]
  /** True when this panel is the multi-member Result's current viewport
   *  pick (the one the user has scrolled into view, per ResultView's
   *  IntersectionObserver). Renders a thin accent border via the
   *  rv-panel--active class. Always false when the parent Result has
   *  one major member — the visual cue is suppressed in that case
   *  because there's nothing to disambiguate. */
  isActive?: boolean
}) {
  // Removal confirmation modes:
  //   'figure'  = standard figure/table remove-from-Result warning
  //   'last'    = blocked because this is the only meaningful member
  //   'version' = hard-delete THIS revision of the figure/table chain
  //   null      = no dialog showing
  const [removeMode, setRemoveMode] = useState<'figure' | 'last' | 'version' | null>(null)
  // Track whether the per-panel ⋯ popover is open.
  const [moreOpen, setMoreOpen] = useState(false)
  const [caption, setCaption] = useState(member.caption ?? '')
  const [text, setText] = useState(member.text ?? '')
  // Track the last server caption we synced to. The picker effect below
  // compares local state against THIS ref (not against the new prop) so
  // it can tell whether the user has an in-flight edit. Pre-2026-06-11
  // the picker compared `prev === member.caption` which used the NEW
  // prop value — meaning once local had ever held a non-empty value,
  // server updates were ignored until a browser refresh. The agent's
  // update_member_caption broadcasts arrived but the chip stayed
  // stale.
  const lastSyncedCaption = useRef(member.caption ?? '')
  useEffect(() => {
    setCaption(member.caption ?? '')
    setText(member.text ?? '')
    lastSyncedCaption.current = member.caption ?? ''
  }, [member.id]) // eslint-disable-line react-hooks/exhaustive-deps
  // Pick up server-side updates to the caption (background auto_interpret
  // daemon completes ~1-3s after pin; agent's update_member_caption
  // broadcasts an entity_updated that triggers a project refetch). Do
  // NOT clobber an in-flight user edit — detected by local state
  // diverging from the last server value we synced.
  useEffect(() => {
    const next = member.caption ?? ''
    setCaption(prev => {
      if (prev === lastSyncedCaption.current) {
        // No local divergence → safe to take the new server value.
        lastSyncedCaption.current = next
        return next
      }
      if (prev === next) {
        // Local already matches the new prop (e.g. the user's own blur
        // round-tripped). Bump the ref forward so subsequent server
        // updates aren't gated on a stale baseline.
        lastSyncedCaption.current = next
        return prev
      }
      // User has an unsaved edit → keep it.
      return prev
    })
  }, [member.caption])

  // ─── Highlight surface state (mirrors Message.tsx's pattern) ──────────
  // contentRef anchors the surface and the rasterization target — set on
  // each render-path's outermost panel div.
  const contentRef = useRef<HTMLDivElement>(null)
  const strokeRef = useRef<Pt[]>([])
  const [stroke, setStroke] = useState<Pt[]>([])
  const [drawing, setDrawing] = useState(false)
  const [busy, setBusy] = useState(false)
  const [hovered, setHovered] = useState(false)
  const canHighlight = !!onAnnotate
  const showSurface = !!highlighting && canHighlight && ((hovered && !anyDrawing) || drawing)
  useEffect(() => { if (!highlighting) { setStroke([]); strokeRef.current = []; setHovered(false) } }, [highlighting])
  // Frozen (pinned) mark — see Message.tsx for the full rationale. After the
  // snapshot is captured the mark stays on this panel until a newer highlight
  // supersedes it or the composer chip is dismissed; App arbitrates ownership
  // via hlOwner against this panel's live capture token. No "invalidate on
  // move" trigger: the overlay is absolute to the panel and the stroke is in
  // [0,1] fractions, so it rides the panel through scroll/reflow.
  const [frozen, setFrozen] = useState<Pt[] | null>(null)
  const myToken = useRef<string | null>(null)
  useEffect(() => { if (hlOwner !== myToken.current) setFrozen(null) }, [hlOwner])

  // Normalize CSS coords to the panel's [0,1] bbox (clamped) so the user can
  // drag past the edge without breaking the stroke.
  function normXY(cx: number, cy: number): Pt {
    const r = contentRef.current!.getBoundingClientRect()
    return {
      x: Math.min(1, Math.max(0, (cx - r.left) / r.width)),
      y: Math.min(1, Math.max(0, (cy - r.top) / r.height)),
    }
  }
  function hlDown(e: React.MouseEvent) {
    const p = normXY(e.clientX, e.clientY)
    strokeRef.current = [p]; setStroke([p]); setDrawing(true); onDrawingChange?.(true)
  }
  // Window-level move/up: stroke continues even if the cursor leaves the
  // panel; release ends it and triggers attach.
  useEffect(() => {
    if (!drawing) return
    function mv(e: MouseEvent) {
      strokeRef.current = [...strokeRef.current, normXY(e.clientX, e.clientY)]
      setStroke(strokeRef.current)
    }
    function up() {
      setDrawing(false); onDrawingChange?.(false)
      if (strokeRef.current.length > 1) attachHighlight()
      else { setStroke([]); strokeRef.current = [] }
    }
    window.addEventListener('mousemove', mv)
    window.addEventListener('mouseup', up)
    return () => { window.removeEventListener('mousemove', mv); window.removeEventListener('mouseup', up) }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [drawing])

  async function attachHighlight() {
    const el = contentRef.current
    const pts = strokeRef.current
    if (!el || pts.length < 2) { setStroke([]); strokeRef.current = []; return }
    setBusy(true)
    try {
      // Cell text fallback — for text/note members, surface the prose so the
      // agent sees what the user actually marked when no subcard was hit.
      const cellText = member.kind === 'text' ? (member.text ?? '') : ''
      // Member is figure-only when no caption text and not a text panel.
      const onlyImage = member.kind === 'figure' && !((member as { caption?: string }).caption || '').trim()
      const result = await captureHighlight({
        cellEl: el,
        ptsNorm: pts,
        subcardSelector: '.rv-panel__cell, .rv-panel__caption, .rv-panel__note, .rv-panel__table',
        describeSubcard: _rvDescribeSubcard,
        entities,
        cellText,
        onlyImage,
      })
      if (result) {
        const token = nextAnnotToken()
        myToken.current = token
        setFrozen([...pts])          // keep the mark on the panel until dismissed
        onAnnotate?.(result, token)
      }
    } catch { /* rasterize failed — drop the mark */ }
    finally { setBusy(false); setStroke([]); strokeRef.current = [] }
  }

  const strokePts = stroke.map(p => `${p.x * 100},${p.y * 100}`).join(' ')
  // Show the frozen mark only while this panel still owns the pinned highlight.
  const frozenActive = !!frozen && frozen.length > 1 && hlOwner != null && hlOwner === myToken.current
  const frozenPts = frozen ? frozen.map(p => `${p.x * 100},${p.y * 100}`).join(' ') : ''

  // Reusable surface JSX, sized to the contentRef wrapper. The active draw
  // surface shows while hovering with mode on (or mid-drag); otherwise, if this
  // panel still owns the pinned highlight, its frozen mark stays put — no draw
  // handler, no hint, click-through so the panel remains interactive.
  const renderHlSurface = () => (
    showSurface ? (
      <div className="rv-panel__hl" onMouseDown={hlDown}>
        {stroke.length > 1 && (
          <svg className="rv-panel__hl-svg" viewBox="0 0 100 100" preserveAspectRatio="none">
            <polyline points={strokePts} fill="none" stroke={HILITE} strokeWidth="16"
                      strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" />
          </svg>
        )}
        <div className="rv-panel__hl-hint">{busy ? 'capturing…' : 'draw to highlight'}</div>
      </div>
    ) : frozenActive ? (
      <div className="rv-panel__hl rv-panel__hl--frozen" aria-hidden>
        <svg className="rv-panel__hl-svg" viewBox="0 0 100 100" preserveAspectRatio="none">
          <polyline points={frozenPts} fill="none" stroke={HILITE} strokeWidth="16"
                    strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" />
        </svg>
      </div>
    ) : null
  )

  const hoverHandlers = {
    onMouseEnter: () => { if (highlighting) setHovered(true) },
    onMouseLeave: () => setHovered(false),
  }

  // Auto-resize the caption textarea to its content. The figure caption is
  // a free-form paragraph (per the new prompt), not a one-liner — without
  // auto-resize the bottom of a multi-sentence caption gets cut off.
  // Includes a ResizeObserver: the panel width changes after mount (image
  // load triggers .focus's vertical scrollbar → panel shrinks by ~15px),
  // text re-wraps to more lines, height must follow. PK 2026-06-09 — live
  // inspect confirmed styleHeight=62px but scrollHeight=100px after layout
  // settled, i.e. text was clipped by ~3 lines.
  const capRef = useRef<HTMLTextAreaElement>(null)
  useLayoutEffect(() => {
    const el = capRef.current
    if (!el) return
    let lastWidth = 0
    const resize = () => {
      const w = el.clientWidth
      if (w === lastWidth) return    // ignore self-triggered height changes
      lastWidth = w
      el.style.height = 'auto'
      el.style.height = el.scrollHeight + 'px'
    }
    resize()
    const ro = new ResizeObserver(resize)
    ro.observe(el)
    return () => ro.disconnect()
  }, [caption])

  const captionOrigin = (member as { caption_origin?: 'ai' | 'user' }).caption_origin ?? 'user'

  // Revision chain for figures. The hook defaults the displayed entity to
  // the LATEST revision (chain[0]); the user can step back via the strip's
  // chevrons. Anchored on the originally-pinned member.ref so the chain
  // stays stable as the agent adds more revisions in the background.
  const rev = useFigureRevisions(member.kind === 'figure' && cell ? cell.id : '', revisionsSignal, entities)
  const displayedFigure: Entity | undefined =
    member.kind === 'figure' ? (rev.displayed ?? cell) : undefined

  // Map a RevisionStrip action onto the chat surface. The displayed entity
  // is sent through so the agent's prefill names the specific revision id
  // (not the anchor + a fuzzy "which one is it" guess).
  const onStripAction = (action: RevisionAction, displayed: Entity) => {
    if (onChatResult) {
      onChatResult(displayed.title, displayed.artifact_path ?? undefined,
                   undefined, action, displayed.id)
    } else if (onAsk) {
      const verb = action === 'reproduce' ? 'Reproduce'
                 : action.startsWith('revision') ? 'Revise'
                 : 'Discuss'
      onAsk(`${verb} "${displayed.title}" in result "${resultTitle}".`)
    }
  }

  // Removing this member: empty notes go silently; figure/table and
  // non-empty notes route through a confirm modal. If this is the only
  // user-meaningful member we instead show a BLOCKING info dialog
  // pointing at the ⋯ menu — the action equals deleting the Result and
  // belongs there, not on a per-figure ×.
  const onRemoveClick = () => {
    const isMeaningful = (
      member.kind === 'figure' || member.kind === 'table' ||
      (member.kind === 'text' && (member.text ?? '').trim() !== '')
    )
    if (!isMeaningful) { onRemove(member.id); return }
    setRemoveMode(isLastNonAutoMember ? 'last' : 'figure')
  }

  // The ⋯ menu replaces the legacy ×. Two affordances:
  //   - "Remove this version" — hard-deletes the currently-displayed
  //     revision of a figure/table chain. Only shown when the chain has
  //     more than one active entry (else the action would empty the chain
  //     and require re-anchoring the member; the "Remove from Result"
  //     path covers that case instead). Destructive: a confirm dialog
  //     spells out that the version goes away permanently but the chain
  //     stays navigable (children re-parent automatically).
  //   - "Remove from Result" — same semantics as the old ×: unlinks the
  //     member, the figure entity (and its whole chain) stays in the
  //     project. The "last meaningful member" guard still applies.
  const chainTotal = (member.kind === 'figure' && rev) ? rev.total : 0
  const canDeleteVersion = chainTotal > 1 && Boolean(onDeleteRevision) && Boolean(displayedFigure)
  const controls = (
    <span className="rv-panel__ctl">
      {count > 1 && <button title="Move up" disabled={idx === 0} onClick={() => onMove(idx, -1)}>↑</button>}
      {count > 1 && <button title="Move down" disabled={idx === count - 1} onClick={() => onMove(idx, 1)}>↓</button>}
      <PanelMoreMenu
        open={moreOpen}
        onToggle={() => setMoreOpen(v => !v)}
        onClose={() => setMoreOpen(false)}
        canDeleteVersion={canDeleteVersion}
        onPickDeleteVersion={() => { setMoreOpen(false); setRemoveMode('version') }}
        onPickRemoveFromResult={() => { setMoreOpen(false); onRemoveClick() }}
      />
    </span>
  )
  const removeDialogs = _removeDialogsFor(
    member, cell, removeMode, setRemoveMode, onRemove,
    displayedFigure, onDeleteRevision, chainTotal,
  )

  // Image-reflow stabilizer (P2): when the displayed revision changes
  // and the new image has a different rendered height, the page jumps.
  // Track the largest rendered height we've observed across this panel's
  // displayed revisions and pin it as a min-height on the cell — the
  // panel only ever grows, never shrinks back, so user reading
  // experience stays stable across chevron clicks.
  const cellRef = useRef<HTMLDivElement>(null)
  const [minCellHeight, setMinCellHeight] = useState<number | null>(null)
  const onImgLoad = (e: React.SyntheticEvent<HTMLImageElement>) => {
    const h = (e.currentTarget as HTMLImageElement).clientHeight
    if (h > 0) setMinCellHeight(prev => (prev == null || h > prev) ? h : prev)
  }

  if (member.kind === 'text') {
    return (
      <>
        <div className={`rv-panel rv-panel--text${isActive ? ' rv-panel--active' : ''}`}
             ref={contentRef} {...hoverHandlers}
             data-member-id={member.id}
             data-active={isActive ? 'true' : 'false'}>
          <textarea className="rv-panel__note" value={text} placeholder="Write a note…" autoFocus={autoFocus}
                    onChange={e => setText(e.target.value)} onBlur={() => onText(member.id, text)} />
          {controls}
          {renderHlSurface()}
        </div>
        {removeDialogs}
      </>
    )
  }

  // Canonical artifact + derived preview. For PNG/JPG `preview` is
  // undefined and we use the canonical directly. For PDF (and other
  // non-raster canonicals), the backend rasterizes a sibling .thumb.png
  // and writes its URL into metadata.preview_path; we use THAT for
  // <img>, and offer the canonical as a download chip so the user
  // grabs the real file (faithful preview, faithful download).
  const canonical = displayedFigure?.artifact_path ?? cell?.artifact_path ?? undefined
  const preview = (displayedFigure?.metadata as { preview_path?: string } | undefined)?.preview_path
    ?? (cell?.metadata as { preview_path?: string } | undefined)?.preview_path
    ?? undefined
  const url = preview ?? canonical
  const isDerivedPreview = Boolean(preview) && preview !== canonical
  const downloadName = canonical
    ? (canonical.split('/').pop() ?? 'figure')
    : 'figure'
  const cellStyle = (member.kind === 'figure' && minCellHeight != null)
    ? { minHeight: minCellHeight } : undefined
  return (
    <div className={`rv-panel${isActive ? ' rv-panel--active' : ''}`}
         ref={contentRef} {...hoverHandlers}
         data-member-id={member.id}
         data-active={isActive ? 'true' : 'false'}>
      <div className="rv-panel__cell" ref={cellRef} style={cellStyle}>
        {member.kind === 'figure' && url
          ? <img className="rv-panel__img" src={url} alt={displayedFigure?.title ?? cell?.title}
                 onLoad={onImgLoad}
                 onClick={() => { if (!highlighting) onZoom(url) }} title="Click to enlarge" />
          : member.kind === 'table'
          ? <button className="rv-panel__table" onClick={() => cell && onFocus(cell.id)}><EntityGlyph name="table" size={16} /> {cell?.title ?? 'table'}</button>
          : <div className="rv-panel__missing">{cell?.title ?? `${member.kind} (unavailable)`}</div>}
        {controls}
      </div>
      {/* RevisionStrip lives BELOW the image: chevrons on the left (if a
          chain exists), SplitButton on the right (Chat default, Revise +
          Reproduce in the dropdown). Non-latest revise triggers a
          confirmation dialog explaining supersession.
          When the canonical is a non-raster (PDF, SVG, …) we surface
          a "↓ original" chip so the user can grab the real artifact
          even though the panel is showing a derived raster preview. */}
      {member.kind === 'figure' && cell && (
        <RevisionStrip
          rev={rev}
          onAction={onStripAction}
          downloadHref={isDerivedPreview ? canonical : undefined}
          downloadLabel={isDerivedPreview ? _canonicalKindLabel(canonical) : undefined}
          downloadName={isDerivedPreview ? downloadName : undefined}
        />
      )}
      <div className="rv-panel__caption-row">
        <textarea ref={capRef} className="rv-panel__caption" value={caption} placeholder="Add a caption…" rows={1}
                  onChange={e => setCaption(e.target.value)}
                  onBlur={() => { if (caption !== (member.caption ?? '')) onCaption(member.id, caption, 'user') }} />
        {captionOrigin === 'ai' && (
          <span className="rv-panel__ai-tag" title="Caption generated by Guide. Edit to claim it as yours.">
            <AgentGlyph agent="guide" size={14} />
          </span>
        )}
      </div>
      {/* Per-panel provenance — this panel's own "how it was made". A Result groups
          independent panels, so provenance lives HERE, not rolled up at the Result
          level. Expanding it never changes focus (only chip clicks navigate). */}
      {cell && (member.kind === 'figure' || member.kind === 'table') && (
        <ProvenanceSection entity={cell} onFocus={onFocus} label="Source" className="prov--panel" />
      )}
      {renderHlSurface()}
      {removeDialogs}
    </div>
  )
}


/** Render the appropriate ⋯ menu confirm dialog given the current mode. */
function _removeDialogsFor(
  member: ResultMember,
  cell: Entity | undefined,
  removeMode: 'figure' | 'last' | 'version' | null,
  setRemoveMode: (m: 'figure' | 'last' | 'version' | null) => void,
  onRemove: (mid: string) => void,
  displayedFigure?: Entity,
  onDeleteRevision?: (entityId: string) => void,
  chainTotal?: number,
) {
  if (!removeMode) return null
  const label = member.kind === 'text'
    ? 'this note'
    : (cell?.title ?? `this ${member.kind}`)

  if (removeMode === 'version' && displayedFigure && onDeleteRevision) {
    const kind = member.kind === 'table' ? 'table' : 'figure'
    const versionLabel = (displayedFigure.title || `this ${kind}`).trim()
    const remaining = Math.max(0, (chainTotal ?? 1) - 1)
    return (
      <ConfirmDialog
        title={`Permanently remove this version?`}
        variant="destructive"
        primaryLabel="Remove this version"
        onPrimary={() => {
          onDeleteRevision(displayedFigure.id)
          setRemoveMode(null)
        }}
        onCancel={() => setRemoveMode(null)}
        body={
          <>
            <p>
              <strong>{versionLabel}</strong> will be deleted permanently.
              The remaining {remaining} version{remaining === 1 ? '' : 's'} in
              the chain stay{remaining === 1 ? 's' : ''} navigable — any newer
              revisions re-link automatically to this version's parent.
            </p>
            <p>
              To remove the whole {kind} (all versions) from this Result
              without deleting anything, use <strong>Remove from Result</strong>
              {' '}in the ⋯ menu instead.
            </p>
          </>
        }
      />
    )
  }

  if (removeMode === 'last') {
    // Blocked: the action equals deleting the Result. Direct to ⋯ menu.
    return (
      <ConfirmDialog
        title="That would empty the Result"
        mode="info"
        variant="info"
        primaryLabel="Got it"
        onPrimary={() => setRemoveMode(null)}
        onCancel={() => setRemoveMode(null)}
        body={
          <>
            <p>
              <strong>{label}</strong> is the only meaningful content in this Result —
              removing it would leave the Result effectively empty.
            </p>
            <p>
              That's equivalent to deleting the Result itself. To do that, use
              the <strong>⋯ menu</strong> next to the Result in the left rail
              (look for <code>Delete</code> there).
            </p>
          </>
        }
      />
    )
  }
  // Standard figure/table removal confirmation
  const kind = member.kind === 'table' ? 'table' : 'figure'
  return (
    <ConfirmDialog
      title={`Remove this ${kind} from the Result?`}
      variant="destructive"
      primaryLabel="Remove"
      onPrimary={() => { onRemove(member.id); setRemoveMode(null) }}
      onCancel={() => setRemoveMode(null)}
      body={
        <>
          <p>
            <strong>{label}</strong> will no longer appear in this Result.
            All of its revisions (the version chain) come off with it.
          </p>
          <p>
            The {kind} entity and its history are <strong>not deleted</strong> —
            they remain in the project and can be re-added to a Result later.
          </p>
        </>
      }
    />
  )
}


/** Per-panel ⋯ button + popover. Replaces the legacy ×.
 *
 * The dropdown holds one or two actions:
 *   - "Remove this version" (only when canDeleteVersion=true): hard-delete
 *     just the currently-displayed revision of the chain. Surfaces a
 *     destructive confirm dialog.
 *   - "Remove from Result" (always): the original × semantics — unlink
 *     the member, the figure entity stays in the project.
 *
 * The popover positions itself with absolute layout inside the panel
 * controls strip (which already lives in rv-panel__cell, position
 * relative). Closes on outside click + on Escape. */
function PanelMoreMenu(props: {
  open: boolean
  onToggle: () => void
  onClose: () => void
  canDeleteVersion: boolean
  onPickDeleteVersion: () => void
  onPickRemoveFromResult: () => void
}) {
  const wrapRef = useRef<HTMLSpanElement>(null)
  useEffect(() => {
    if (!props.open) return
    const onDown = (e: MouseEvent) => {
      if (!wrapRef.current?.contains(e.target as Node)) props.onClose()
    }
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') props.onClose() }
    document.addEventListener('mousedown', onDown)
    document.addEventListener('keydown', onKey)
    return () => {
      document.removeEventListener('mousedown', onDown)
      document.removeEventListener('keydown', onKey)
    }
  }, [props])
  return (
    <span ref={wrapRef} className="rv-panel__more-wrap">
      <button
        className="rv-panel__more-btn"
        title="Panel actions"
        aria-label="Panel actions"
        aria-haspopup="menu"
        aria-expanded={props.open}
        onClick={e => { e.stopPropagation(); props.onToggle() }}
      >⋯</button>
      {props.open && (
        <div className="rv-panel__more-pop" role="menu">
          {props.canDeleteVersion && (
            <button
              role="menuitem"
              className="rv-panel__more-item rv-panel__more-danger"
              onClick={props.onPickDeleteVersion}
            >Remove this version</button>
          )}
          <button
            role="menuitem"
            className="rv-panel__more-item"
            onClick={props.onPickRemoveFromResult}
          >Remove from Result</button>
        </div>
      )}
    </span>
  )
}
