#!/usr/bin/env python3
"""Regenerate CATALOG.md by scanning every <id>/scenario.yaml (v1 single-prompt
AND v2 multi-step/lifecycle). Unlike _make_specs.py (which authors the v1 specs),
this only INDEXES whatever is on disk, so hand-authored v2 scenarios are included.

    python _make_catalog.py
"""
import os, glob, collections, yaml

HERE = os.path.dirname(os.path.abspath(__file__))


def main():
    os.chdir(HERE)
    dirs = sorted(d for d in os.listdir(".")
                  if os.path.isdir(d) and os.path.isfile(os.path.join(d, "scenario.yaml")))
    rows, lc, dom = [], collections.Counter(), collections.Counter()
    for d in dirs:
        spec = yaml.safe_load(open(f"{d}/scenario.yaml")) or {}
        steps = spec.get("steps")
        if steps:
            ver, n = "v2", len(steps)
            kinds = sorted({s.get("kind") for s in steps if s.get("kind") and s.get("kind") != "normal"})
            for k in kinds:
                lc[k] += 1
            summ = spec.get("summary") or spec.get("title") or ""
        else:
            ver, n, kinds, summ = "v1", 1, [], spec.get("title", "")
        db = sum(os.path.getsize(f) for f in glob.glob(f"{d}/data/**", recursive=True) if os.path.isfile(f))
        rows.append((d, spec.get("domain", "?"), ver, n, ",".join(kinds), db, summ))
        dom[spec.get("domain", "?")] += 1

    def sz(b):
        return "—" if not b else (f"{b//1024} KB" if b < 1024**2 else f"{b/1024**2:.1f} MB")

    L = [f"# Scenario catalog\n",
         f"Auto-generated by `_make_catalog.py` — index of all **{len(rows)}** scenarios. "
         "v1 = single-prompt; v2 = multi-step lifecycle (see `SCHEMA.md`).\n",
         "| id | domain | schema | steps | lifecycle | data | summary |",
         "|---|---|---|---|---|---|---|"]
    for d, dm, ver, n, k, db, s in rows:
        s = s.replace("|", "/")
        s = s[:67] + "..." if len(s) > 70 else s
        L.append(f"| `{d}` | {dm} | {ver} | {n} | {k or '—'} | {sz(db)} | {s} |")
    L += ["", "## Domain coverage", "| domain | count |", "|---|---|"]
    L += [f"| {dm} | {c} |" for dm, c in dom.most_common()]
    L += ["", "## Lifecycle-event coverage (v2 scenarios)",
          "Scenarios exercising each project-lifecycle event.\n",
          "| event | scenarios |", "|---|---|"]
    L += [f"| {k} | {lc.get(k, 0)} |" for k in
          ["revise", "resume", "branch", "drop", "delete", "version_change"]]
    open("CATALOG.md", "w").write("\n".join(L) + "\n")
    print(f"wrote CATALOG.md ({len(rows)} scenarios)")


if __name__ == "__main__":
    main()
