#!/usr/bin/env python3
"""Derive the CUDA flavour of a base env pack — one source spec, two flavours.

    derive_gpu_pack.py <base_pack.yaml> --cuda-ceiling 13.3 [-o OUT.yaml]

A GPU deployment does not swap its base for a CUDA one — the CUDA science stack
is ~5x the disk (measured 2026-08-13: python-bio 676 MB -> 3.4 GB compressed,
2.5 GB -> 6.5 GB realized), and only Slurm *jobs* can reach the GPU node, so
dragging it into every interactive session would cost everyone and serve nobody.
Instead the site publishes a second flavour of the SAME pack that only GPU jobs
ride (site.yaml `jobs.gpu_env_pack`, resolved by `base_env.gpu_pack_env_id`).

Deriving it mechanically — at deploy time, from the shipped base spec — is what
keeps the two flavours from drifting: hand-maintained CPU and CUDA specs WILL
diverge, and then the same analysis gives different answers depending on which
lane ran it, which is worse than having no GPU support at all. The derived file
carries a GENERATED header; editing it is editing the wrong file.

What changes, and why (the shape comes from weft/gpu.py::suggest_gpu_spec):
  * a `linux-64` VARIANT gains `pytorch-gpu` + `cuda-version <=<ceiling>` — a
    CEILING at the site driver's max CUDA, not an equality pin, so the solver
    takes the best userland the driver supports and a driver upgrade needs no
    spec edit. Shared deps are byte-identical to the source pack.
  * `system_requirements: {cuda: <ceiling>}` — pixi's mechanism for solving a
    GPU stack on a GPU-less controller.
  * `platforms: [linux-64]` — this flavour exists for cluster jobs only. macOS
    needs no flavour at all: the default osx-arm64 builds ship Metal/MPS, so
    the UNMODIFIED base pack already accelerates there.
  * `role: gpu` (not `base`) — two `role: base` packs for one language would
    make base resolution ambiguous. `default_state: "off"` + empty `first_use`:
    nothing materializes this eagerly or on import-trigger; the job lane
    resolves it by name, deliberately outside the modules gate.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("derive_gpu_pack: PyYAML required")

GPU_SUFFIX = "-cuda"


def derive(doc: dict, ceiling: str) -> dict:
    """Pure: source pack doc -> CUDA-flavour doc. Raises ValueError on a doc
    that is not a base pack or already carries an accelerator variant."""
    if not isinstance(doc, dict) or not doc.get("name") or "spec" not in doc:
        raise ValueError("not a pack spec (need `name:` and `spec:`)")
    if str(doc.get("role", "base")) != "base":
        raise ValueError(f"source pack has role {doc.get('role')!r} — derive "
                         f"from the base pack, not from a derived one")
    spec = doc.get("spec") or {}
    if "variants" in spec or str(doc["name"]).endswith(GPU_SUFFIX):
        raise ValueError("source already carries a variant/flavour — refuse to "
                         "stack a second derivation on it")
    out = {
        "name": doc["name"] + GPU_SUFFIX,
        "title": f"{doc.get('title') or doc['name']} (CUDA)",
        "languages": list(doc.get("languages") or []),
        # never eagerly materialized, never first-use triggered — job-lane only
        "default_state": "off",
        "first_use": [],
        "role": "gpu",
    }
    if doc.get("import_names"):
        out["import_names"] = dict(doc["import_names"])
    new_spec = {k: v for k, v in spec.items() if k != "platforms"}
    new_spec["platforms"] = ["linux-64"]
    new_spec["system_requirements"] = {"cuda": str(ceiling)}
    new_spec["variants"] = {
        "linux-64": {"conda": ["pytorch-gpu", f"cuda-version <={ceiling}"]}}
    out["spec"] = new_spec
    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(prog="derive-gpu-pack",
                                 description="Derive a pack's CUDA flavour.")
    ap.add_argument("source", help="base pack yaml (e.g. install/core/envs/python_bio.yaml)")
    ap.add_argument("--cuda-ceiling", required=True,
                    help="the GPU nodes' driver max CUDA (nvidia-smi header), e.g. 13.3")
    ap.add_argument("-o", "--out", help="output path (default: stdout)")
    a = ap.parse_args(argv)

    src = Path(a.source)
    try:
        doc = yaml.safe_load(src.read_text())
        derived = derive(doc, a.cuda_ceiling)
    except (OSError, yaml.YAMLError, ValueError) as e:
        print(f"derive-gpu-pack: {e}", file=sys.stderr)
        return 2

    header = (f"# GENERATED by scripts/derive_gpu_pack.py from {src.name} "
              f"(cuda ceiling {a.cuda_ceiling}) — DO NOT EDIT.\n"
              f"# Re-derive after changing the source pack; hand edits drift the\n"
              f"# CPU and CUDA flavours apart, and the same analysis then behaves\n"
              f"# differently depending on which lane ran it.\n")
    text = header + yaml.safe_dump(derived, sort_keys=False, default_flow_style=False)
    if a.out:
        Path(a.out).write_text(text)
        print(f"wrote {a.out}")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
