"""The three Compute-port Protocols (misc/weft_rewrite.md §3).

These are aba-side *seams*, not processes: `WeftAdapter` implements all three
over one embedded `Weft` instance. The Protocols exist so (a) consumers name
the port they need — which keeps the per-port call set measurable (the §3
pass-target: could SitePort fold away?) — and (b) tests can substitute fakes
per port without a weft install.

Method signatures mirror weft's tool API 1:1 (near-pure pass-through by
design); everything is async — the adapter runs the sync weft calls on a
dedicated thread pool. All methods raise `ComputeError` on a weft error
payload and return the success payload dict otherwise.

The sets below are the calls the W0–W3 plan needs. Extend a port when a phase
starts consuming a new call — never reach around the ports to `weft` directly
(guarded by test_compute_ports.py).
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class SitePort(Protocol):
    """Site registration + decision-grade discovery (deploy/doctor-facing)."""

    async def register_site(self, name: str, kind: str, config: dict, **kw) -> dict: ...
    async def sites_list(self) -> list[dict]: ...
    async def sites_describe(self, name: str) -> dict: ...
    async def site_associations(self, name: str) -> dict: ...
    async def site_probe(self, name: str) -> dict: ...
    async def site_probe_deep(self, name: str, partitions: list[str] | None = None, **kw) -> dict: ...
    async def site_load(self, name: str, resources: dict | None = None, **kw) -> dict: ...
    async def module_list(self, site: str, search: str | None = None, **kw) -> dict: ...
    async def site_note(self, name: str, note: str) -> dict: ...
    async def site_footprint(self, site: str) -> dict: ...
    async def site_unregister(self, name: str) -> dict: ...
    # site-scoped reclamation (Settings→Compute "Free up": plan → confirm-gated sweep)
    async def gc_plan(self, site: str | None = None) -> dict: ...
    async def gc_sweep(self, site: str, confirm: bool = False) -> dict: ...
    async def doctor(self) -> dict: ...
    async def reconcile(self) -> list[dict]: ...


@runtime_checkable
class EnvPort(Protocol):
    """Environments: ensure/layer/session/publish — every env is an EnvID."""

    async def env_ensure(self, spec_or_id: Any, update: bool = False, **kw) -> dict: ...
    async def env_status(self, env_id: str) -> dict: ...
    async def env_revise(self, env_id: str, reason: str = "") -> dict: ...
    async def env_find_near(self, spec: dict, site: str | None = None, **kw) -> dict: ...
    async def env_why(self, env_id: str, package: str) -> dict: ...
    async def env_repair(self, env_id: str, site: str) -> dict: ...
    async def env_evict(self, env_id: str, site: str, **kw) -> dict: ...
    async def env_gpu_hint(self, site: str) -> dict: ...
    async def list_envs(self) -> dict: ...
    async def session_start(self, spec_or_env_id: Any, site: str) -> dict: ...
    async def session_exec(self, session_id: str, cmd: str) -> dict: ...
    async def session_install(self, session_id: str, **kw) -> dict: ...
    async def session_run_installer(self, session_id: str, cmd: str, **kw) -> dict: ...
    async def session_snapshot(self, session_id: str, **kw) -> dict: ...
    async def session_stop(self, session_id: str) -> dict: ...
    # publish/adopt base catalog (W3 — declared now; the OOD ownership model)
    async def env_publish(self, env_id: str, site: str, tree: str, name: str, **kw) -> dict: ...
    async def env_adopt(self, site: str, tree: str, name: str, **kw) -> dict: ...
    async def env_published(self, site: str, tree: str) -> dict: ...
    async def env_unpublish(self, site: str, tree: str, name: str, version: str, **kw) -> dict: ...


@runtime_checkable
class RunPort(Protocol):
    """Execution: kernels / tasks / arrays / services / events / provenance."""

    async def task_submit(self, task: dict, **kw) -> dict: ...
    async def task_status(self, job_id: str | None = None, **kw) -> list[dict]: ...
    async def task_logs(self, job_id: str, **kw) -> dict: ...
    async def task_result(self, job_id: str) -> dict: ...
    async def task_cancel(self, job_id: str, why: str = "") -> dict: ...
    async def jobs_where(self, **kw) -> dict: ...
    async def array_status(self, group: str) -> dict: ...
    async def array_elements(self, group: str, **kw) -> dict: ...
    async def array_retry(self, group: str, **kw) -> dict: ...
    async def array_result(self, group: str) -> dict: ...
    async def kernel_start(self, site: str, lang: str = "python", **kw) -> dict: ...
    async def kernel_exec(self, kernel_id: str, code: str, **kw) -> dict: ...
    async def kernel_poll(self, kernel_id: str, block: int, **kw) -> dict: ...
    async def kernel_peek(self, kernel_id: str, block: int, **kw) -> dict: ...
    async def kernel_status(self, kernel_id: str) -> dict: ...
    async def kernel_transcript(self, kernel_id: str, **kw) -> list[dict]: ...
    async def kernel_interrupt(self, kernel_id: str) -> dict: ...
    async def kernel_restart(self, kernel_id: str, **kw) -> dict: ...
    async def kernel_promote(self, kernel_id: str, blocks: list[int]) -> dict: ...
    async def kernel_stop(self, kernel_id: str) -> dict: ...
    async def list_kernels(self, **kw) -> dict: ...
    # retention of run outputs (weft/misc/retention.md) — inventory + keep + GC
    async def run_inventory(self, target: str, **kw) -> dict: ...
    async def run_retain(self, target: str, **kw) -> dict: ...
    async def run_discard(self, target: str) -> dict: ...
    async def run_forget(self, **kw) -> dict: ...
    async def retained_runs(self, **kw) -> list[dict]: ...
    async def service_start(self, site: str, task: dict, ports: list[int], **kw) -> dict: ...
    async def service_status(self, service_id: str) -> dict: ...
    async def service_stop(self, service_id: str, **kw) -> dict: ...
    async def list_services(self, **kw) -> dict: ...
    async def job_node_exec(self, job_id: str, cmd: str, why: str, **kw) -> dict: ...
    async def events_poll(self, since_cursor: int = 0, **kw) -> Any: ...
    async def provenance(self, target: str, depth: int = 5) -> dict: ...
    async def bundle_export(self, job_id: str, out_path: str, **kw) -> dict: ...
    async def bundle_import(self, path: str) -> dict: ...
    async def data_register(self, path: str, **kw) -> dict: ...
    async def data_describe(self, ref: str) -> dict: ...
    async def data_fetch(self, ref: str, to_path: str) -> dict: ...
